#!/bin/bash
#
# buildwget
#
# -- This script downloads and installs the GNU wget file retrieval package
#    (https://www.gnu.org/software/wget/)
#
# OpenCoarrays is distributed under the OSI-approved BSD 3-clause License:
# Copyright (c) 2015, Sourcery, Inc.
# Copyright (c) 2015, Sourcery Institute
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, 
# are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this 
#    list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice, this 
#    list of conditions and the following disclaimer in the documentation and/or 
#    other materials provided with the distribution.
# 3. Neither the names of the copyright holders nor the names of their contributors 
#    may be used to endorse or promote products derived from this software without 
#    specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
# IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT 
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR 
# PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, 
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.

cmd=`basename $0` 
usage()
{
    echo ""
    echo " $cmd - Bash script for building wget from source"
    echo ""
    echo " Usage (optional arguments in square brackets): "
    echo "      $cmd <version-number> [<installation-path> <number-of-threads>]"
    echo " or   $cmd [options] "
    echo ""
    echo " Options:"
    echo "   --help, -h           Show this help message"
    echo "   --version, -v, -V    Show this help message"
    echo ""
    echo " Example usage:"
    echo ""
    echo "   $cmd default"
    echo "   $cmd 1.16.3"
    echo "   $cmd 1.16.3 /opt/ftp/1.16.3 4"
    echo "   $cmd --help"
    echo ""
    echo " Note: For a list of available wget versions, visit"
    echo " http://ftp.gnu.org/gnu/wget/?C=M;O=D"
    echo ""
    exit 1
}

# Default to installing wget 1.16.3 if no version specified in the first
# command-line argument
if [[ $1 == 'default' ]]; then
  version=1.16.3
else
  version=$1 
fi

build_path=${PWD}/wget-$version-build

# Default to installing in the present working directory if no install path is specified:
if [ -z $2 ]; then
  install_path=$build_path
else
  install_path=$2
fi

# Default to 2 threads if no specified thread count:
if [ -z $3 ]; then
  num_threads=1
else
  num_threads=$3
fi

check_prerequisites()
{
  # If there are no user-specified compilers in the path, default to gcc/g++.
  if [ -z $CC ]; then
    CC=gcc
  fi  
  if [ -z $CXX ]; then
    CXX=g++
  fi 
  # Verify that 'ftp' is is in the path.
  if ! type ftp > /dev/null; then
    echo 
    echo "$cmd requires 'ftp'.  Please ensure that it is installed and in your path.  Aborting." 
    exit 1
  fi
  if ! type make > /dev/null; then
    echo 
    echo "$cmd requires 'make'.  Please ensure that it is installed and in your path.  Aborting." 
    exit 1
  fi
}

# Download wget if the tar ball is not already in the present working directory
download()
{
  if [ ! -f "wget-$version.tar.xz" ]; then
    echo "Downloading wget-$version.tar.xz"
    ftp -n ftp://ftp.gnu.org<<END_SCRIPT
    cd gnu
    cd wget
    get wget-1.16.3.tar.xz
    quit
END_SCRIPT
  else 
    echo "Found wget-$version.tar.xz in the current directory.  Skipping download"
  fi
}

# Unpack wget if the unpacked tar ball is not in the present working directory
unpack()
{
  if [ ! -d "wget-$version" ]; then
    echo "Unpacking wget-$version.tar.xz"
    tar xf wget-$version.tar.xz 
  fi
}

# Make the build directory, configure, and build
build()
{
  echo "Building wget"
  mkdir -p $build_path &&
  cd $build_path &&
  ../wget-$version/configure --prefix=$install_path #&&
  CC=$CC CXX=$CXX make -j $num_threads
}

if [ $# == 0 ]; then
  # Print usage information if script is invoked without arguments
  usage | less
elif [[ $1 == '--help' || $1 == '-h' ]]; then
  # Print usage information if script is invoked with --help or -h argument
  usage | less
elif [[ $1 == '-v' || $1 == '-V' || $1 == '--version' ]]; then
  # Print script copyright if invoked with -v, -V, or --version argument
  echo ""
  echo "wget Build Script"
  echo "Copyright (C) 2015 Sourcery, Inc."
  echo "Copyright (C) 2015 Sourcery Institute"
  echo ""
  echo "$cmd comes with NO WARRANTY, to the extent permitted by law."
  echo "You may redistribute copies of $cmd under the terms of the"
  echo "BSD 3-Clause License.  For more information about these matters, see"
  echo "http://www.sourceryinstitute.org/license.html"
  echo ""
else
  # Download, unpack, and build CMake
  time \
  {
    check_prerequisites &&
    download &&
    unpack  &&
    CC=$CC CXX=$CXX build $version $install_path $num_threads
  } >&1 | tee build.log
  echo ""
  echo "Check build.log for results.  If the build was successful, type"
  echo "'cd wget-$version-build && make install' (or 'cd wget-$version-build && sudo make install')"
  echo "to complete the installation, after which wget will be in the 'bin' subdirectory of $install_path" 
  echo ""
fi
