! Generated by cart. DO NOT EDIT
program main
    implicit none

    if (.not.run()) stop 1
contains
    function run() result(passed)
        use co_broadcast_test, only: &
                co_broadcast_co_broadcast => &
                    test_co_broadcast
        use co_max_test, only: &
                co_max_co_max => &
                    test_co_max
        use co_min_test, only: &
                co_min_co_min => &
                    test_co_min
        use co_reduce_test, only: &
                co_reduce_co_reduce => &
                    test_co_reduce
        use co_sum_test, only: &
                co_sum_co_sum => &
                    test_co_sum
        use error_stop_test, only: &
                error_stop_this_image => &
                    test_this_image
        use num_images_test, only: &
                num_images_num_images => &
                    test_num_images
        use this_image_test, only: &
                this_image_this_image => &
                    test_this_image
        use garden , only: test_item_t, test_that, run_tests



        logical :: passed

        type(test_item_t) :: tests
        type(test_item_t) :: individual_tests(8)

        individual_tests(1) = co_broadcast_co_broadcast()
        individual_tests(2) = co_max_co_max()
        individual_tests(3) = co_min_co_min()
        individual_tests(4) = co_reduce_co_reduce()
        individual_tests(5) = co_sum_co_sum()
        individual_tests(6) = error_stop_this_image()
        individual_tests(7) = num_images_num_images()
        individual_tests(8) = this_image_this_image()
        tests = test_that(individual_tests)


        passed = run_tests(tests)

    end function
end program
