/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2+fortran
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGFORTRAN
#define SWIGFORTRAN
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif


#include <assert.h>
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { printf("In " DECL ": " MSG); assert(0); RETURNNULL; }


enum {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
};


#define SWIG_check_nonnull(PTR, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
  if (!(PTR)) { \
    SWIG_exception_impl(FUNCNAME, SWIG_NullReferenceError, \
                        "Cannot pass null " TYPENAME " (class " FNAME ") " \
                        "as a reference", RETURNNULL); \
  }


#include <stdio.h>
#if (defined(_MSC_VER) && (_MSC_VER < 1900)) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIGVERSION 0x040002 
#define SWIG_VERSION SWIGVERSION


#define SWIG_as_voidptr(a) (void *)((const void *)(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a)) 


typedef struct {
    void* cptr;
    int cmemflags;
} SwigClassWrapper;


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.cptr = NULL;
    result.cmemflags = 0;
    return result;
}


#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


#include <string.h>


SWIGINTERN void SWIG_assign(SwigClassWrapper* self, SwigClassWrapper other) {
  if (self->cptr == NULL) {
    /* LHS is unassigned */
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture pointer from RHS, clear 'moving' flag */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_RVALUE);
    } else {
      /* Become a reference to the other object */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_OWN);
    }
  } else if (other.cptr == NULL) {
    /* Replace LHS with a null pointer */
    free(self->cptr);
    *self = SwigClassWrapper_uninitialized();
  } else if (self->cptr == other.cptr) {
    /* Self-assignment: ignore */
  } else {
    if (self->cmemflags & SWIG_MEM_OWN) {
      free(self->cptr);
    }
    self->cptr = other.cptr;
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_RVALUE;
    } else {
      /* Point to RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_OWN;
    }
  }
}

SWIGEXPORT void _wrap_descriptor_dimension__stride_set(SwigClassWrapper *farg1, long const *farg2) {
  struct descriptor_dimension *arg1 = (struct descriptor_dimension *) 0 ;
  ptrdiff_t arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct descriptor_dimension *", "descriptor_dimension", "descriptor_dimension::_stride", return );
  arg1 = (struct descriptor_dimension *)farg1->cptr;
  arg2 = (ptrdiff_t)(*farg2);
  if (arg1) (arg1)->_stride = arg2;
}


SWIGEXPORT long _wrap_descriptor_dimension__stride_get(SwigClassWrapper *farg1) {
  long fresult ;
  struct descriptor_dimension *arg1 = (struct descriptor_dimension *) 0 ;
  ptrdiff_t result;
  
  SWIG_check_nonnull(farg1->cptr, "struct descriptor_dimension *", "descriptor_dimension", "descriptor_dimension::_stride", return 0);
  arg1 = (struct descriptor_dimension *)farg1->cptr;
  result = (ptrdiff_t) ((arg1)->_stride);
  fresult = (ptrdiff_t)(result);
  return fresult;
}


SWIGEXPORT void _wrap_descriptor_dimension_lower_bound_set(SwigClassWrapper *farg1, long const *farg2) {
  struct descriptor_dimension *arg1 = (struct descriptor_dimension *) 0 ;
  ptrdiff_t arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct descriptor_dimension *", "descriptor_dimension", "descriptor_dimension::lower_bound", return );
  arg1 = (struct descriptor_dimension *)farg1->cptr;
  arg2 = (ptrdiff_t)(*farg2);
  if (arg1) (arg1)->lower_bound = arg2;
}


SWIGEXPORT long _wrap_descriptor_dimension_lower_bound_get(SwigClassWrapper *farg1) {
  long fresult ;
  struct descriptor_dimension *arg1 = (struct descriptor_dimension *) 0 ;
  ptrdiff_t result;
  
  SWIG_check_nonnull(farg1->cptr, "struct descriptor_dimension *", "descriptor_dimension", "descriptor_dimension::lower_bound", return 0);
  arg1 = (struct descriptor_dimension *)farg1->cptr;
  result = (ptrdiff_t) ((arg1)->lower_bound);
  fresult = (ptrdiff_t)(result);
  return fresult;
}


SWIGEXPORT void _wrap_descriptor_dimension__ubound_set(SwigClassWrapper *farg1, long const *farg2) {
  struct descriptor_dimension *arg1 = (struct descriptor_dimension *) 0 ;
  ptrdiff_t arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct descriptor_dimension *", "descriptor_dimension", "descriptor_dimension::_ubound", return );
  arg1 = (struct descriptor_dimension *)farg1->cptr;
  arg2 = (ptrdiff_t)(*farg2);
  if (arg1) (arg1)->_ubound = arg2;
}


SWIGEXPORT long _wrap_descriptor_dimension__ubound_get(SwigClassWrapper *farg1) {
  long fresult ;
  struct descriptor_dimension *arg1 = (struct descriptor_dimension *) 0 ;
  ptrdiff_t result;
  
  SWIG_check_nonnull(farg1->cptr, "struct descriptor_dimension *", "descriptor_dimension", "descriptor_dimension::_ubound", return 0);
  arg1 = (struct descriptor_dimension *)farg1->cptr;
  result = (ptrdiff_t) ((arg1)->_ubound);
  fresult = (ptrdiff_t)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_descriptor_dimension() {
  SwigClassWrapper fresult ;
  struct descriptor_dimension *result = 0 ;
  
  result = (struct descriptor_dimension *)calloc(1, sizeof(struct descriptor_dimension));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_descriptor_dimension(SwigClassWrapper *farg1) {
  struct descriptor_dimension *arg1 = (struct descriptor_dimension *) 0 ;
  
  arg1 = (struct descriptor_dimension *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_descriptor_dimension_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct descriptor_dimension *arg1 = (struct descriptor_dimension *) 0 ;
  struct descriptor_dimension *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT void _wrap_gfc_descriptor_t_base_addr_set(SwigClassWrapper *farg1, void const **farg2) {
  struct gfc_descriptor_t *arg1 = (struct gfc_descriptor_t *) 0 ;
  void *arg2 = (void *) 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct gfc_descriptor_t *", "gfc_descriptor_t", "gfc_descriptor_t::base_addr", return );
  arg1 = (struct gfc_descriptor_t *)farg1->cptr;
  arg2 = (void *)(*farg2);
  if (arg1) (arg1)->base_addr = arg2;
}


SWIGEXPORT void * _wrap_gfc_descriptor_t_base_addr_get(SwigClassWrapper *farg1) {
  void * fresult ;
  struct gfc_descriptor_t *arg1 = (struct gfc_descriptor_t *) 0 ;
  void *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct gfc_descriptor_t *", "gfc_descriptor_t", "gfc_descriptor_t::base_addr", return 0);
  arg1 = (struct gfc_descriptor_t *)farg1->cptr;
  result = (void *) ((arg1)->base_addr);
  fresult = (void *)(result);
  return fresult;
}


SWIGEXPORT void _wrap_gfc_descriptor_t_offset_set(SwigClassWrapper *farg1, size_t const *farg2) {
  struct gfc_descriptor_t *arg1 = (struct gfc_descriptor_t *) 0 ;
  size_t arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct gfc_descriptor_t *", "gfc_descriptor_t", "gfc_descriptor_t::offset", return );
  arg1 = (struct gfc_descriptor_t *)farg1->cptr;
  arg2 = (size_t)(*farg2);
  if (arg1) (arg1)->offset = arg2;
}


SWIGEXPORT size_t _wrap_gfc_descriptor_t_offset_get(SwigClassWrapper *farg1) {
  size_t fresult ;
  struct gfc_descriptor_t *arg1 = (struct gfc_descriptor_t *) 0 ;
  size_t result;
  
  SWIG_check_nonnull(farg1->cptr, "struct gfc_descriptor_t *", "gfc_descriptor_t", "gfc_descriptor_t::offset", return 0);
  arg1 = (struct gfc_descriptor_t *)farg1->cptr;
  result = (size_t) ((arg1)->offset);
  fresult = (size_t)(result);
  return fresult;
}


SWIGEXPORT void _wrap_gfc_descriptor_t_dtype_set(SwigClassWrapper *farg1, long const *farg2) {
  struct gfc_descriptor_t *arg1 = (struct gfc_descriptor_t *) 0 ;
  ptrdiff_t arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct gfc_descriptor_t *", "gfc_descriptor_t", "gfc_descriptor_t::dtype", return );
  arg1 = (struct gfc_descriptor_t *)farg1->cptr;
  arg2 = (ptrdiff_t)(*farg2);
  if (arg1) (arg1)->dtype = arg2;
}


SWIGEXPORT long _wrap_gfc_descriptor_t_dtype_get(SwigClassWrapper *farg1) {
  long fresult ;
  struct gfc_descriptor_t *arg1 = (struct gfc_descriptor_t *) 0 ;
  ptrdiff_t result;
  
  SWIG_check_nonnull(farg1->cptr, "struct gfc_descriptor_t *", "gfc_descriptor_t", "gfc_descriptor_t::dtype", return 0);
  arg1 = (struct gfc_descriptor_t *)farg1->cptr;
  result = (ptrdiff_t) ((arg1)->dtype);
  fresult = (ptrdiff_t)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_gfc_descriptor_t_dim_get(SwigClassWrapper *farg1) {
  SwigClassWrapper fresult ;
  struct gfc_descriptor_t *arg1 = (struct gfc_descriptor_t *) 0 ;
  descriptor_dimension *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct gfc_descriptor_t *", "gfc_descriptor_t", "gfc_descriptor_t::dim", return SwigClassWrapper_uninitialized());
  arg1 = (struct gfc_descriptor_t *)farg1->cptr;
  result = (descriptor_dimension *)(descriptor_dimension *) ((arg1)->dim);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_gfc_descriptor_t() {
  SwigClassWrapper fresult ;
  struct gfc_descriptor_t *result = 0 ;
  
  result = (struct gfc_descriptor_t *)calloc(1, sizeof(struct gfc_descriptor_t));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_gfc_descriptor_t(SwigClassWrapper *farg1) {
  struct gfc_descriptor_t *arg1 = (struct gfc_descriptor_t *) 0 ;
  
  arg1 = (struct gfc_descriptor_t *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_gfc_descriptor_t_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct gfc_descriptor_t *arg1 = (struct gfc_descriptor_t *) 0 ;
  struct gfc_descriptor_t *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT int _wrap_GFC_MAX_DIMENSIONS_get() {
  int fresult ;
  int result;
  
  result = (int)(7);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_GFC_DTYPE_RANK_MASK_get() {
  int fresult ;
  int result;
  
  result = (int)(0x07);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_GFC_DTYPE_TYPE_SHIFT_get() {
  int fresult ;
  int result;
  
  result = (int)(3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_GFC_DTYPE_TYPE_MASK_get() {
  int fresult ;
  int result;
  
  result = (int)(0x38);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_GFC_DTYPE_SIZE_SHIFT_get() {
  int fresult ;
  int result;
  
  result = (int)(6);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_GFC_DTYPE_CHARACTER_get() {
  int fresult ;
  int result;
  
  result = (int)(48);
  fresult = (int)(result);
  return fresult;
}



