! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.2+fortran
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.
module libcaf_m
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS
 public :: get_STAT_UNLOCKED
 public :: get_STAT_LOCKED
 public :: get_STAT_LOCKED_OTHER_IMAGE
 public :: get_STAT_DUP_SYNC_IMAGES
 public :: get_STAT_STOPPED_IMAGE
 public :: get_STAT_FAILED_IMAGE
 ! enum caf_register_t
 enum, bind(c)
  enumerator :: CAF_REGTYPE_COARRAY_STATIC
  enumerator :: CAF_REGTYPE_COARRAY_ALLOC
  enumerator :: CAF_REGTYPE_LOCK_STATIC
  enumerator :: CAF_REGTYPE_LOCK_ALLOC
  enumerator :: CAF_REGTYPE_CRITICAL
  enumerator :: CAF_REGTYPE_EVENT_STATIC
  enumerator :: CAF_REGTYPE_EVENT_ALLOC
  enumerator :: CAF_REGTYPE_COARRAY_ALLOC_REGISTER_ONLY
  enumerator :: CAF_REGTYPE_COARRAY_ALLOC_ALLOCATE_ONLY
 end enum
 integer, parameter, public :: caf_register_t = kind(CAF_REGTYPE_COARRAY_STATIC)
 public :: CAF_REGTYPE_COARRAY_STATIC, CAF_REGTYPE_COARRAY_ALLOC, CAF_REGTYPE_LOCK_STATIC, CAF_REGTYPE_LOCK_ALLOC, &
    CAF_REGTYPE_CRITICAL, CAF_REGTYPE_EVENT_STATIC, CAF_REGTYPE_EVENT_ALLOC, CAF_REGTYPE_COARRAY_ALLOC_REGISTER_ONLY, &
    CAF_REGTYPE_COARRAY_ALLOC_ALLOCATE_ONLY
 ! enum caf_deregister_t
 enum, bind(c)
  enumerator :: CAF_DEREGTYPE_COARRAY_DEREGISTER
  enumerator :: CAF_DEREGTYPE_COARRAY_DEALLOCATE_ONLY
 end enum
 integer, parameter, public :: caf_deregister_t = kind(CAF_DEREGTYPE_COARRAY_DEREGISTER)
 public :: CAF_DEREGTYPE_COARRAY_DEREGISTER, CAF_DEREGTYPE_COARRAY_DEALLOCATE_ONLY

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 ! struct struct caf_teams_list
 type, public :: caf_teams_list
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_team => swigf_caf_teams_list_team_set
  procedure :: get_team => swigf_caf_teams_list_team_get
  procedure :: set_team_id => swigf_caf_teams_list_team_id_set
  procedure :: get_team_id => swigf_caf_teams_list_team_id_get
  procedure :: set_prev => swigf_caf_teams_list_prev_set
  procedure :: get_prev => swigf_caf_teams_list_prev_get
  procedure :: release => swigf_caf_teams_list_release
  procedure, private :: swigf_caf_teams_list_op_assign__
  generic :: assignment(=) => swigf_caf_teams_list_op_assign__
 end type caf_teams_list
 ! struct struct caf_used_teams_list
 type, public :: caf_used_teams_list
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_team_list_elem => swigf_caf_used_teams_list_team_list_elem_set
  procedure :: get_team_list_elem => swigf_caf_used_teams_list_team_list_elem_get
  procedure :: set_prev => swigf_caf_used_teams_list_prev_set
  procedure :: get_prev => swigf_caf_used_teams_list_prev_get
  procedure :: release => swigf_caf_used_teams_list_release
  procedure, private :: swigf_caf_used_teams_list_op_assign__
  generic :: assignment(=) => swigf_caf_used_teams_list_op_assign__
 end type caf_used_teams_list
 ! struct struct caf_vector_t
 type, public :: caf_vector_t
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_nvec => swigf_caf_vector_t_nvec_set
  procedure :: get_nvec => swigf_caf_vector_t_nvec_get
  procedure :: get_u => swigf_caf_vector_t_u_get
  procedure :: release => swigf_caf_vector_t_release
  procedure, private :: swigf_caf_vector_t_op_assign__
  generic :: assignment(=) => swigf_caf_vector_t_op_assign__
 end type caf_vector_t
 ! union caf_vector_t_u
 type, public :: caf_vector_t_u
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: get_v => swigf_caf_vector_t_u_v_get
  procedure :: get_triplet => swigf_caf_vector_t_u_triplet_get
  procedure :: release => swigf_caf_vector_t_u_release
  procedure, private :: swigf_caf_vector_t_u_op_assign__
  generic :: assignment(=) => swigf_caf_vector_t_u_op_assign__
 end type caf_vector_t_u
 ! struct caf_vector_t_u_triplet
 type, public :: caf_vector_t_u_triplet
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_lower_bound => swigf_caf_vector_t_u_triplet_lower_bound_set
  procedure :: get_lower_bound => swigf_caf_vector_t_u_triplet_lower_bound_get
  procedure :: set_upper_bound => swigf_caf_vector_t_u_triplet_upper_bound_set
  procedure :: get_upper_bound => swigf_caf_vector_t_u_triplet_upper_bound_get
  procedure :: set_stride => swigf_caf_vector_t_u_triplet_stride_set
  procedure :: get_stride => swigf_caf_vector_t_u_triplet_stride_get
  procedure :: release => swigf_caf_vector_t_u_triplet_release
  procedure, private :: swigf_caf_vector_t_u_triplet_op_assign__
  generic :: assignment(=) => swigf_caf_vector_t_u_triplet_op_assign__
 end type caf_vector_t_u_triplet
 ! struct caf_vector_t_u_v
 type, public :: caf_vector_t_u_v
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_vector => swigf_caf_vector_t_u_v_vector_set
  procedure :: get_vector => swigf_caf_vector_t_u_v_vector_get
  procedure :: set_kind => swigf_caf_vector_t_u_v_kind_set
  procedure :: get_kind => swigf_caf_vector_t_u_v_kind_get
  procedure :: release => swigf_caf_vector_t_u_v_release
  procedure, private :: swigf_caf_vector_t_u_v_op_assign__
  generic :: assignment(=) => swigf_caf_vector_t_u_v_op_assign__
 end type caf_vector_t_u_v
 public :: get_GFC_CAF_BYREF
 public :: get_GFC_CAF_HIDDENLEN
 public :: get_GFC_CAF_ARG_VALUE
 public :: get_GFC_CAF_ARG_DESC
 type, public :: SWIGTYPE_p_gfc_descriptor_t
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: is_contiguous
 type, public :: SWIGTYPE_p_int
  type(SwigClassWrapper), public :: swigdata
 end type
 type, public :: SWIGTYPE_p_p_p_char
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: init
 public :: finalize
 public :: this_image
 public :: num_images
 type, bind(C) :: SwigArrayWrapper
  type(C_PTR), public :: data = C_NULL_PTR
  integer(C_SIZE_T), public :: size = 0
 end type
 type, public :: SWIGTYPE_p_p_void
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: deregister
 public :: caf_get
 public :: caf_send
 public :: caf_sendget
 public :: co_broadcast
 public :: co_max
 public :: co_min
 public :: SWIGTYPE_f_p_void_p_void__p_void
 public :: co_reduce
 public :: co_sum
 public :: sync_all
 public :: sync_images
 public :: sync_memory
 public :: stop_str
 public :: stop
 public :: error_stop_str
 public :: error_stop
 public :: fail_image
 public :: form_team
 public :: change_team
 public :: end_team
 public :: sync_team
 public :: team_number
 public :: image_status
 public :: failed_images
 public :: stopped_images
 public :: atomic_define
 public :: atomic_ref
 public :: atomic_cas
 public :: atomic_op
 public :: lock
 public :: unlock
 public :: event_post
 public :: event_wait
 public :: event_query
 interface caf_vector_t_u
  module procedure swigf_new_caf_vector_t_u
 end interface
 interface caf_vector_t_u_v
  module procedure swigf_new_caf_vector_t_u_v
 end interface
 interface caf_teams_list
  module procedure swigf_new_caf_teams_list
 end interface
 interface caf_used_teams_list
  module procedure swigf_new_caf_used_teams_list
 end interface
 interface caf_vector_t
  module procedure swigf_new_caf_vector_t
 end interface
 interface caf_vector_t_u_triplet
  module procedure swigf_new_caf_vector_t_u_triplet
 end interface

! FUNCTION POINTER DECLARATIONS
abstract interface
function SWIGTYPE_f_p_void_p_void__p_void(arg0, arg1) &
bind(C) &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in), value :: arg0
type(C_PTR), intent(in), value :: arg1
type(C_PTR) :: fresult
end function

end interface


! WRAPPER DECLARATIONS
interface
function swigc_STAT_UNLOCKED_get() &
bind(C, name="_wrap_STAT_UNLOCKED_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: fresult
end function

function swigc_STAT_LOCKED_get() &
bind(C, name="_wrap_STAT_LOCKED_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: fresult
end function

function swigc_STAT_LOCKED_OTHER_IMAGE_get() &
bind(C, name="_wrap_STAT_LOCKED_OTHER_IMAGE_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: fresult
end function

function swigc_STAT_DUP_SYNC_IMAGES_get() &
bind(C, name="_wrap_STAT_DUP_SYNC_IMAGES_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: fresult
end function

function swigc_STAT_STOPPED_IMAGE_get() &
bind(C, name="_wrap_STAT_STOPPED_IMAGE_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: fresult
end function

function swigc_STAT_FAILED_IMAGE_get() &
bind(C, name="_wrap_STAT_FAILED_IMAGE_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: fresult
end function

subroutine swigc_caf_teams_list_team_set(farg1, farg2) &
bind(C, name="_wrap_caf_teams_list_team_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(C_PTR), intent(in) :: farg2
end subroutine

function swigc_caf_teams_list_team_get(farg1) &
bind(C, name="_wrap_caf_teams_list_team_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_caf_teams_list_team_id_set(farg1, farg2) &
bind(C, name="_wrap_caf_teams_list_team_id_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_caf_teams_list_team_id_get(farg1) &
bind(C, name="_wrap_caf_teams_list_team_id_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_caf_teams_list_prev_set(farg1, farg2) &
bind(C, name="_wrap_caf_teams_list_prev_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_caf_teams_list_prev_get(farg1) &
bind(C, name="_wrap_caf_teams_list_prev_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_caf_teams_list() &
bind(C, name="_wrap_new_caf_teams_list") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_caf_teams_list(farg1) &
bind(C, name="_wrap_delete_caf_teams_list")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_caf_teams_list_op_assign__(farg1, farg2) &
bind(C, name="_wrap_caf_teams_list_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_caf_used_teams_list_team_list_elem_set(farg1, farg2) &
bind(C, name="_wrap_caf_used_teams_list_team_list_elem_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_caf_used_teams_list_team_list_elem_get(farg1) &
bind(C, name="_wrap_caf_used_teams_list_team_list_elem_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_caf_used_teams_list_prev_set(farg1, farg2) &
bind(C, name="_wrap_caf_used_teams_list_prev_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_caf_used_teams_list_prev_get(farg1) &
bind(C, name="_wrap_caf_used_teams_list_prev_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_caf_used_teams_list() &
bind(C, name="_wrap_new_caf_used_teams_list") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_caf_used_teams_list(farg1) &
bind(C, name="_wrap_delete_caf_used_teams_list")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_caf_used_teams_list_op_assign__(farg1, farg2) &
bind(C, name="_wrap_caf_used_teams_list_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_caf_vector_t_nvec_set(farg1, farg2) &
bind(C, name="_wrap_caf_vector_t_nvec_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
end subroutine

function swigc_caf_vector_t_nvec_get(farg1) &
bind(C, name="_wrap_caf_vector_t_nvec_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T) :: fresult
end function

function swigc_caf_vector_t_u_get(farg1) &
bind(C, name="_wrap_caf_vector_t_u_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_caf_vector_t() &
bind(C, name="_wrap_new_caf_vector_t") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_caf_vector_t(farg1) &
bind(C, name="_wrap_delete_caf_vector_t")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_caf_vector_t_op_assign__(farg1, farg2) &
bind(C, name="_wrap_caf_vector_t_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_caf_vector_t_u_v_get(farg1) &
bind(C, name="_wrap_caf_vector_t_u_v_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_caf_vector_t_u_triplet_get(farg1) &
bind(C, name="_wrap_caf_vector_t_u_triplet_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_caf_vector_t_u() &
bind(C, name="_wrap_new_caf_vector_t_u") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_caf_vector_t_u(farg1) &
bind(C, name="_wrap_delete_caf_vector_t_u")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_caf_vector_t_u_op_assign__(farg1, farg2) &
bind(C, name="_wrap_caf_vector_t_u_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_caf_vector_t_u_triplet_lower_bound_set(farg1, farg2) &
bind(C, name="_wrap_caf_vector_t_u_triplet_lower_bound_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

function swigc_caf_vector_t_u_triplet_lower_bound_get(farg1) &
bind(C, name="_wrap_caf_vector_t_u_triplet_lower_bound_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_caf_vector_t_u_triplet_upper_bound_set(farg1, farg2) &
bind(C, name="_wrap_caf_vector_t_u_triplet_upper_bound_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

function swigc_caf_vector_t_u_triplet_upper_bound_get(farg1) &
bind(C, name="_wrap_caf_vector_t_u_triplet_upper_bound_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_LONG) :: fresult
end function

subroutine swigc_caf_vector_t_u_triplet_stride_set(farg1, farg2) &
bind(C, name="_wrap_caf_vector_t_u_triplet_stride_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_LONG), intent(in) :: farg2
end subroutine

function swigc_caf_vector_t_u_triplet_stride_get(farg1) &
bind(C, name="_wrap_caf_vector_t_u_triplet_stride_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_LONG) :: fresult
end function

function swigc_new_caf_vector_t_u_triplet() &
bind(C, name="_wrap_new_caf_vector_t_u_triplet") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_caf_vector_t_u_triplet(farg1) &
bind(C, name="_wrap_delete_caf_vector_t_u_triplet")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_caf_vector_t_u_triplet_op_assign__(farg1, farg2) &
bind(C, name="_wrap_caf_vector_t_u_triplet_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_caf_vector_t_u_v_vector_set(farg1, farg2) &
bind(C, name="_wrap_caf_vector_t_u_v_vector_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(C_PTR), intent(in) :: farg2
end subroutine

function swigc_caf_vector_t_u_v_vector_get(farg1) &
bind(C, name="_wrap_caf_vector_t_u_v_vector_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_caf_vector_t_u_v_kind_set(farg1, farg2) &
bind(C, name="_wrap_caf_vector_t_u_v_kind_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_caf_vector_t_u_v_kind_get(farg1) &
bind(C, name="_wrap_caf_vector_t_u_v_kind_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

function swigc_new_caf_vector_t_u_v() &
bind(C, name="_wrap_new_caf_vector_t_u_v") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_caf_vector_t_u_v(farg1) &
bind(C, name="_wrap_delete_caf_vector_t_u_v")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_caf_vector_t_u_v_op_assign__(farg1, farg2) &
bind(C, name="_wrap_caf_vector_t_u_v_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_GFC_CAF_BYREF_get() &
bind(C, name="_wrap_GFC_CAF_BYREF_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: fresult
end function

function swigc_GFC_CAF_HIDDENLEN_get() &
bind(C, name="_wrap_GFC_CAF_HIDDENLEN_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: fresult
end function

function swigc_GFC_CAF_ARG_VALUE_get() &
bind(C, name="_wrap_GFC_CAF_ARG_VALUE_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: fresult
end function

function swigc_GFC_CAF_ARG_DESC_get() &
bind(C, name="_wrap_GFC_CAF_ARG_DESC_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: fresult
end function

function swigc_is_contiguous(farg1) &
bind(C, name="_wrap_is_contiguous") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_init(farg1, farg2) &
bind(C, name="_wrap_init")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_finalize() &
bind(C, name="_wrap_finalize")
use, intrinsic :: ISO_C_BINDING
end subroutine

function swigc_this_image(farg1) &
bind(C, name="_wrap_this_image") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
integer(C_INT) :: fresult
end function

function swigc_num_images(farg1, farg2) &
bind(C, name="_wrap_num_images") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

subroutine swigc_deregister(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_deregister")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
type(SwigArrayWrapper) :: farg3
integer(C_INT), intent(in) :: farg4
end subroutine

subroutine swigc_caf_get(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10) &
bind(C, name="_wrap_caf_get")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(C_PTR), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(SwigClassWrapper), intent(in) :: farg4
type(SwigClassWrapper), intent(in) :: farg5
type(SwigClassWrapper), intent(in) :: farg6
integer(C_INT), intent(in) :: farg7
integer(C_INT), intent(in) :: farg8
integer(C_INT), intent(in) :: farg9
type(SwigClassWrapper), intent(in) :: farg10
end subroutine

subroutine swigc_caf_send(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10) &
bind(C, name="_wrap_caf_send")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(C_PTR), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(SwigClassWrapper), intent(in) :: farg4
type(SwigClassWrapper), intent(in) :: farg5
type(SwigClassWrapper), intent(in) :: farg6
integer(C_INT), intent(in) :: farg7
integer(C_INT), intent(in) :: farg8
integer(C_INT), intent(in) :: farg9
type(SwigClassWrapper), intent(in) :: farg10
end subroutine

subroutine swigc_caf_sendget(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, &
  farg14) &
bind(C, name="_wrap_caf_sendget")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(C_PTR), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(SwigClassWrapper), intent(in) :: farg4
type(SwigClassWrapper), intent(in) :: farg5
type(C_PTR), intent(in) :: farg6
integer(C_SIZE_T), intent(in) :: farg7
integer(C_INT), intent(in) :: farg8
type(SwigClassWrapper), intent(in) :: farg9
type(SwigClassWrapper), intent(in) :: farg10
integer(C_INT), intent(in) :: farg11
integer(C_INT), intent(in) :: farg12
integer(C_INT), intent(in) :: farg13
type(SwigClassWrapper), intent(in) :: farg14
end subroutine

subroutine swigc_co_broadcast(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_co_broadcast")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
type(SwigArrayWrapper) :: farg4
integer(C_INT), intent(in) :: farg5
end subroutine

subroutine swigc_co_max(farg1, farg2, farg3, farg4, farg5, farg6) &
bind(C, name="_wrap_co_max")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
type(SwigArrayWrapper) :: farg4
integer(C_INT), intent(in) :: farg5
integer(C_INT), intent(in) :: farg6
end subroutine

subroutine swigc_co_min(farg1, farg2, farg3, farg4, farg5, farg6) &
bind(C, name="_wrap_co_min")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
type(SwigArrayWrapper) :: farg4
integer(C_INT), intent(in) :: farg5
integer(C_INT), intent(in) :: farg6
end subroutine

subroutine swigc_co_reduce(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8) &
bind(C, name="_wrap_co_reduce")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper), intent(in) :: farg1
type(C_FUNPTR), value :: farg2
integer(C_INT), intent(in) :: farg3
integer(C_INT), intent(in) :: farg4
type(SwigClassWrapper), intent(in) :: farg5
type(SwigArrayWrapper) :: farg6
integer(C_INT), intent(in) :: farg7
integer(C_INT), intent(in) :: farg8
end subroutine

subroutine swigc_co_sum(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_co_sum")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
type(SwigArrayWrapper) :: farg4
integer(C_INT), intent(in) :: farg5
end subroutine

subroutine swigc_sync_all(farg1, farg2, farg3) &
bind(C, name="_wrap_sync_all")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigArrayWrapper) :: farg2
integer(C_INT), intent(in) :: farg3
end subroutine

subroutine swigc_sync_images(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_sync_images")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
integer(C_INT), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
type(SwigArrayWrapper) :: farg4
integer(C_INT), intent(in) :: farg5
end subroutine

subroutine swigc_sync_memory(farg1, farg2, farg3) &
bind(C, name="_wrap_sync_memory")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigArrayWrapper) :: farg2
integer(C_INT), intent(in) :: farg3
end subroutine

subroutine swigc_stop_str(farg1, farg2) &
bind(C, name="_wrap_stop_str")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

subroutine swigc_stop(farg1) &
bind(C, name="_wrap_stop")
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
end subroutine

subroutine swigc_error_stop_str(farg1, farg2) &
bind(C, name="_wrap_error_stop_str")
use, intrinsic :: ISO_C_BINDING
import :: swigarraywrapper
type(SwigArrayWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

subroutine swigc_error_stop(farg1) &
bind(C, name="_wrap_error_stop")
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
end subroutine

subroutine swigc_fail_image() &
bind(C, name="_wrap_fail_image")
use, intrinsic :: ISO_C_BINDING
end subroutine

subroutine swigc_form_team(farg1, farg2, farg3) &
bind(C, name="_wrap_form_team")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_INT), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
end subroutine

subroutine swigc_change_team(farg1, farg2) &
bind(C, name="_wrap_change_team")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

subroutine swigc_end_team(farg1) &
bind(C, name="_wrap_end_team")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_sync_team(farg1, farg2) &
bind(C, name="_wrap_sync_team")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_team_number(farg1) &
bind(C, name="_wrap_team_number") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

function swigc_image_status(farg1) &
bind(C, name="_wrap_image_status") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_failed_images(farg1, farg2, farg3) &
bind(C, name="_wrap_failed_images")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
end subroutine

subroutine swigc_stopped_images(farg1, farg2, farg3) &
bind(C, name="_wrap_stopped_images")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
end subroutine

subroutine swigc_atomic_define(farg1, farg2, farg3, farg4, farg5, farg6, farg7) &
bind(C, name="_wrap_atomic_define")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(C_PTR), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(C_PTR), intent(in) :: farg4
type(SwigClassWrapper), intent(in) :: farg5
integer(C_INT), intent(in) :: farg6
integer(C_INT), intent(in) :: farg7
end subroutine

subroutine swigc_atomic_ref(farg1, farg2, farg3, farg4, farg5, farg6, farg7) &
bind(C, name="_wrap_atomic_ref")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(C_PTR), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(C_PTR), intent(in) :: farg4
type(SwigClassWrapper), intent(in) :: farg5
integer(C_INT), intent(in) :: farg6
integer(C_INT), intent(in) :: farg7
end subroutine

subroutine swigc_atomic_cas(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9) &
bind(C, name="_wrap_atomic_cas")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(C_PTR), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(C_PTR), intent(in) :: farg4
type(C_PTR), intent(in) :: farg5
type(C_PTR), intent(in) :: farg6
type(SwigClassWrapper), intent(in) :: farg7
integer(C_INT), intent(in) :: farg8
integer(C_INT), intent(in) :: farg9
end subroutine

subroutine swigc_atomic_op(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9) &
bind(C, name="_wrap_atomic_op")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_INT), intent(in) :: farg1
type(C_PTR), intent(in) :: farg2
integer(C_SIZE_T), intent(in) :: farg3
integer(C_INT), intent(in) :: farg4
type(C_PTR), intent(in) :: farg5
type(C_PTR), intent(in) :: farg6
type(SwigClassWrapper), intent(in) :: farg7
integer(C_INT), intent(in) :: farg8
integer(C_INT), intent(in) :: farg9
end subroutine

subroutine swigc_lock(farg1, farg2, farg3, farg4, farg5, farg6, farg7) &
bind(C, name="_wrap_lock")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(C_PTR), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(SwigClassWrapper), intent(in) :: farg4
type(SwigClassWrapper), intent(in) :: farg5
type(SwigArrayWrapper) :: farg6
integer(C_INT), intent(in) :: farg7
end subroutine

subroutine swigc_unlock(farg1, farg2, farg3, farg4, farg5, farg6) &
bind(C, name="_wrap_unlock")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(C_PTR), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(SwigClassWrapper), intent(in) :: farg4
type(SwigArrayWrapper) :: farg5
integer(C_INT), intent(in) :: farg6
end subroutine

subroutine swigc_event_post(farg1, farg2, farg3, farg4, farg5, farg6) &
bind(C, name="_wrap_event_post")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(C_PTR), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(SwigClassWrapper), intent(in) :: farg4
type(SwigArrayWrapper) :: farg5
integer(C_INT), intent(in) :: farg6
end subroutine

subroutine swigc_event_wait(farg1, farg2, farg3, farg4, farg5, farg6) &
bind(C, name="_wrap_event_wait")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
import :: swigarraywrapper
type(C_PTR), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(SwigClassWrapper), intent(in) :: farg4
type(SwigArrayWrapper) :: farg5
integer(C_INT), intent(in) :: farg6
end subroutine

subroutine swigc_event_query(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_event_query")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(C_PTR), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_INT), intent(in) :: farg3
type(SwigClassWrapper), intent(in) :: farg4
type(SwigClassWrapper), intent(in) :: farg5
end subroutine

end interface


contains
 ! MODULE SUBPROGRAMS
function get_STAT_UNLOCKED() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT) :: fresult 

fresult = swigc_STAT_UNLOCKED_get()
swig_result = fresult
end function

function get_STAT_LOCKED() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT) :: fresult 

fresult = swigc_STAT_LOCKED_get()
swig_result = fresult
end function

function get_STAT_LOCKED_OTHER_IMAGE() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT) :: fresult 

fresult = swigc_STAT_LOCKED_OTHER_IMAGE_get()
swig_result = fresult
end function

function get_STAT_DUP_SYNC_IMAGES() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT) :: fresult 

fresult = swigc_STAT_DUP_SYNC_IMAGES_get()
swig_result = fresult
end function

function get_STAT_STOPPED_IMAGE() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT) :: fresult 

fresult = swigc_STAT_STOPPED_IMAGE_get()
swig_result = fresult
end function

function get_STAT_FAILED_IMAGE() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT) :: fresult 

fresult = swigc_STAT_FAILED_IMAGE_get()
swig_result = fresult
end function

subroutine swigf_caf_teams_list_team_set(self, team)
use, intrinsic :: ISO_C_BINDING
class(caf_teams_list), intent(in) :: self
type(C_PTR), intent(in) :: team
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = team
call swigc_caf_teams_list_team_set(farg1, farg2)
end subroutine

function swigf_caf_teams_list_team_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
class(caf_teams_list), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_teams_list_team_get(farg1)
swig_result = fresult
end function

subroutine swigf_caf_teams_list_team_id_set(self, team_id)
use, intrinsic :: ISO_C_BINDING
class(caf_teams_list), intent(in) :: self
integer(C_INT), intent(in) :: team_id
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = team_id
call swigc_caf_teams_list_team_id_set(farg1, farg2)
end subroutine

function swigf_caf_teams_list_team_id_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(caf_teams_list), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_teams_list_team_id_get(farg1)
swig_result = fresult
end function

subroutine swigf_caf_teams_list_prev_set(self, prev)
use, intrinsic :: ISO_C_BINDING
class(caf_teams_list), intent(in) :: self
class(caf_teams_list), intent(in) :: prev
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = prev%swigdata
call swigc_caf_teams_list_prev_set(farg1, farg2)
end subroutine

function swigf_caf_teams_list_prev_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(caf_teams_list) :: swig_result
class(caf_teams_list), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_teams_list_prev_get(farg1)
swig_result%swigdata = fresult
end function

function swigf_new_caf_teams_list() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(caf_teams_list) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_caf_teams_list()
self%swigdata = fresult
end function

subroutine swigf_caf_teams_list_release(self)
use, intrinsic :: ISO_C_BINDING
class(caf_teams_list), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_caf_teams_list(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_caf_teams_list_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(caf_teams_list), intent(inout) :: self
type(caf_teams_list), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_caf_teams_list_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_caf_used_teams_list_team_list_elem_set(self, team_list_elem)
use, intrinsic :: ISO_C_BINDING
class(caf_used_teams_list), intent(in) :: self
class(caf_teams_list), intent(in) :: team_list_elem
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = team_list_elem%swigdata
call swigc_caf_used_teams_list_team_list_elem_set(farg1, farg2)
end subroutine

function swigf_caf_used_teams_list_team_list_elem_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(caf_teams_list) :: swig_result
class(caf_used_teams_list), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_used_teams_list_team_list_elem_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_caf_used_teams_list_prev_set(self, prev)
use, intrinsic :: ISO_C_BINDING
class(caf_used_teams_list), intent(in) :: self
class(caf_used_teams_list), intent(in) :: prev
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = prev%swigdata
call swigc_caf_used_teams_list_prev_set(farg1, farg2)
end subroutine

function swigf_caf_used_teams_list_prev_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(caf_used_teams_list) :: swig_result
class(caf_used_teams_list), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_used_teams_list_prev_get(farg1)
swig_result%swigdata = fresult
end function

function swigf_new_caf_used_teams_list() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(caf_used_teams_list) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_caf_used_teams_list()
self%swigdata = fresult
end function

subroutine swigf_caf_used_teams_list_release(self)
use, intrinsic :: ISO_C_BINDING
class(caf_used_teams_list), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_caf_used_teams_list(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_caf_used_teams_list_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(caf_used_teams_list), intent(inout) :: self
type(caf_used_teams_list), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_caf_used_teams_list_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_caf_vector_t_nvec_set(self, nvec)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t), intent(in) :: self
integer(C_SIZE_T), intent(in) :: nvec
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 

farg1 = self%swigdata
farg2 = nvec
call swigc_caf_vector_t_nvec_set(farg1, farg2)
end subroutine

function swigf_caf_vector_t_nvec_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_SIZE_T) :: swig_result
class(caf_vector_t), intent(in) :: self
integer(C_SIZE_T) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_vector_t_nvec_get(farg1)
swig_result = fresult
end function

function swigf_caf_vector_t_u_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(caf_vector_t_u) :: swig_result
class(caf_vector_t), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_vector_t_u_get(farg1)
swig_result%swigdata = fresult
end function

function swigf_new_caf_vector_t() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(caf_vector_t) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_caf_vector_t()
self%swigdata = fresult
end function

subroutine swigf_caf_vector_t_release(self)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_caf_vector_t(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_caf_vector_t_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t), intent(inout) :: self
type(caf_vector_t), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_caf_vector_t_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function swigf_caf_vector_t_u_v_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(caf_vector_t_u_v) :: swig_result
class(caf_vector_t_u), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_vector_t_u_v_get(farg1)
swig_result%swigdata = fresult
end function

function swigf_caf_vector_t_u_triplet_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(caf_vector_t_u_triplet) :: swig_result
class(caf_vector_t_u), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_vector_t_u_triplet_get(farg1)
swig_result%swigdata = fresult
end function

function swigf_new_caf_vector_t_u() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(caf_vector_t_u) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_caf_vector_t_u()
self%swigdata = fresult
end function

subroutine swigf_caf_vector_t_u_release(self)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t_u), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_caf_vector_t_u(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_caf_vector_t_u_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t_u), intent(inout) :: self
type(caf_vector_t_u), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_caf_vector_t_u_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_caf_vector_t_u_triplet_lower_bound_set(self, lower_bound)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t_u_triplet), intent(in) :: self
integer(C_LONG), intent(in) :: lower_bound
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = lower_bound
call swigc_caf_vector_t_u_triplet_lower_bound_set(farg1, farg2)
end subroutine

function swigf_caf_vector_t_u_triplet_lower_bound_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
class(caf_vector_t_u_triplet), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_vector_t_u_triplet_lower_bound_get(farg1)
swig_result = fresult
end function

subroutine swigf_caf_vector_t_u_triplet_upper_bound_set(self, upper_bound)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t_u_triplet), intent(in) :: self
integer(C_LONG), intent(in) :: upper_bound
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = upper_bound
call swigc_caf_vector_t_u_triplet_upper_bound_set(farg1, farg2)
end subroutine

function swigf_caf_vector_t_u_triplet_upper_bound_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
class(caf_vector_t_u_triplet), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_vector_t_u_triplet_upper_bound_get(farg1)
swig_result = fresult
end function

subroutine swigf_caf_vector_t_u_triplet_stride_set(self, stride)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t_u_triplet), intent(in) :: self
integer(C_LONG), intent(in) :: stride
type(SwigClassWrapper) :: farg1 
integer(C_LONG) :: farg2 

farg1 = self%swigdata
farg2 = stride
call swigc_caf_vector_t_u_triplet_stride_set(farg1, farg2)
end subroutine

function swigf_caf_vector_t_u_triplet_stride_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_LONG) :: swig_result
class(caf_vector_t_u_triplet), intent(in) :: self
integer(C_LONG) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_vector_t_u_triplet_stride_get(farg1)
swig_result = fresult
end function

function swigf_new_caf_vector_t_u_triplet() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(caf_vector_t_u_triplet) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_caf_vector_t_u_triplet()
self%swigdata = fresult
end function

subroutine swigf_caf_vector_t_u_triplet_release(self)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t_u_triplet), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_caf_vector_t_u_triplet(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_caf_vector_t_u_triplet_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t_u_triplet), intent(inout) :: self
type(caf_vector_t_u_triplet), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_caf_vector_t_u_triplet_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_caf_vector_t_u_v_vector_set(self, vector)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t_u_v), intent(in) :: self
type(C_PTR), intent(in) :: vector
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = vector
call swigc_caf_vector_t_u_v_vector_set(farg1, farg2)
end subroutine

function swigf_caf_vector_t_u_v_vector_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
class(caf_vector_t_u_v), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_vector_t_u_v_vector_get(farg1)
swig_result = fresult
end function

subroutine swigf_caf_vector_t_u_v_kind_set(self, kind)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t_u_v), intent(in) :: self
integer(C_INT), intent(in) :: kind
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = kind
call swigc_caf_vector_t_u_v_kind_set(farg1, farg2)
end subroutine

function swigf_caf_vector_t_u_v_kind_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(caf_vector_t_u_v), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_caf_vector_t_u_v_kind_get(farg1)
swig_result = fresult
end function

function swigf_new_caf_vector_t_u_v() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(caf_vector_t_u_v) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_caf_vector_t_u_v()
self%swigdata = fresult
end function

subroutine swigf_caf_vector_t_u_v_release(self)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t_u_v), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_caf_vector_t_u_v(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_caf_vector_t_u_v_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(caf_vector_t_u_v), intent(inout) :: self
type(caf_vector_t_u_v), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_caf_vector_t_u_v_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function get_GFC_CAF_BYREF() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT) :: fresult 

fresult = swigc_GFC_CAF_BYREF_get()
swig_result = fresult
end function

function get_GFC_CAF_HIDDENLEN() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT) :: fresult 

fresult = swigc_GFC_CAF_HIDDENLEN_get()
swig_result = fresult
end function

function get_GFC_CAF_ARG_VALUE() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT) :: fresult 

fresult = swigc_GFC_CAF_ARG_VALUE_get()
swig_result = fresult
end function

function get_GFC_CAF_ARG_DESC() &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT) :: fresult 

fresult = swigc_GFC_CAF_ARG_DESC_get()
swig_result = fresult
end function


subroutine SWIGTM_fout_bool(imout, fout)
  use, intrinsic :: ISO_C_BINDING
  integer(kind=C_INT), intent(in) :: imout
  logical, intent(out) :: fout
  fout = (imout /= 0)
end subroutine

function is_contiguous(arg0) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg0
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
fresult = swigc_is_contiguous(farg1)
call SWIGTM_fout_bool(fresult, swig_result)
end function

subroutine init(arg0, arg1)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_int), intent(in) :: arg0
class(SWIGTYPE_p_p_p_char), intent(in) :: arg1
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = arg0%swigdata
farg2 = arg1%swigdata
call swigc_init(farg1, farg2)
end subroutine

subroutine finalize()
use, intrinsic :: ISO_C_BINDING

call swigc_finalize()
end subroutine

function this_image(arg0) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT), intent(in) :: arg0
integer(C_INT) :: fresult 
integer(C_INT) :: farg1 

farg1 = arg0
fresult = swigc_this_image(farg1)
swig_result = fresult
end function

function num_images(arg0, arg1) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT), intent(in) :: arg0
integer(C_INT), intent(in) :: arg1
integer(C_INT) :: fresult 
integer(C_INT) :: farg1 
integer(C_INT) :: farg2 

farg1 = arg0
farg2 = arg1
fresult = swigc_num_images(farg1, farg2)
swig_result = fresult
end function


subroutine SWIGTM_fin_char_Sm_(finp, iminp, temp)
  use, intrinsic :: ISO_C_BINDING
  character(len=*), intent(in) :: finp
  type(SwigArrayWrapper), intent(out) :: iminp
  character(kind=C_CHAR), dimension(:), target, allocatable, intent(out) :: temp
  integer :: i

  allocate(character(kind=C_CHAR) :: temp(len(finp) + 1))
  do i=1,len(finp)
    temp(i) = char(ichar(finp(i:i)), kind=C_CHAR)
  end do
  i = len(finp) + 1
  temp(i) = C_NULL_CHAR ! C finp compatibility
  iminp%data = c_loc(temp)
  iminp%size = len(finp, kind=C_SIZE_T)
end subroutine

subroutine deregister(arg0, arg1, arg2, arg3)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_p_void), intent(in) :: arg0
class(SWIGTYPE_p_int), intent(in) :: arg1
character(len=*), target :: arg2
integer(C_INT), intent(in) :: arg3
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg3_temp 
type(SwigArrayWrapper) :: farg3 
integer(C_INT) :: farg4 

farg1 = arg0%swigdata
farg2 = arg1%swigdata
call SWIGTM_fin_char_Sm_(arg2, farg3, farg3_temp)
farg4 = arg3
call swigc_deregister(farg1, farg2, farg3, farg4)
end subroutine


subroutine SWIGTM_fin_bool(finp, iminp)
  use, intrinsic :: ISO_C_BINDING
  logical, intent(in) :: finp
  integer(kind=C_INT), intent(out) :: iminp
  if (finp .eqv. .true.) then
    iminp = 1
  else
    iminp = 0
  end if
end subroutine

subroutine caf_get(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: arg0
integer(C_SIZE_T), intent(in) :: arg1
integer(C_INT), intent(in) :: arg2
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg3
class(caf_vector_t), intent(in) :: arg4
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg5
integer(C_INT), intent(in) :: arg6
integer(C_INT), intent(in) :: arg7
logical, intent(in) :: arg8
class(SWIGTYPE_p_int), intent(in) :: arg9
type(C_PTR) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INT) :: farg3 
type(SwigClassWrapper) :: farg4 
type(SwigClassWrapper) :: farg5 
type(SwigClassWrapper) :: farg6 
integer(C_INT) :: farg7 
integer(C_INT) :: farg8 
integer(C_INT) :: farg9 
type(SwigClassWrapper) :: farg10 

farg1 = arg0
farg2 = arg1
farg3 = arg2
farg4 = arg3%swigdata
farg5 = arg4%swigdata
farg6 = arg5%swigdata
farg7 = arg6
farg8 = arg7
call SWIGTM_fin_bool(arg8, farg9)
farg10 = arg9%swigdata
call swigc_caf_get(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10)
end subroutine

subroutine caf_send(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: arg0
integer(C_SIZE_T), intent(in) :: arg1
integer(C_INT), intent(in) :: arg2
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg3
class(caf_vector_t), intent(in) :: arg4
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg5
integer(C_INT), intent(in) :: arg6
integer(C_INT), intent(in) :: arg7
logical, intent(in) :: arg8
class(SWIGTYPE_p_int), intent(in) :: arg9
type(C_PTR) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INT) :: farg3 
type(SwigClassWrapper) :: farg4 
type(SwigClassWrapper) :: farg5 
type(SwigClassWrapper) :: farg6 
integer(C_INT) :: farg7 
integer(C_INT) :: farg8 
integer(C_INT) :: farg9 
type(SwigClassWrapper) :: farg10 

farg1 = arg0
farg2 = arg1
farg3 = arg2
farg4 = arg3%swigdata
farg5 = arg4%swigdata
farg6 = arg5%swigdata
farg7 = arg6
farg8 = arg7
call SWIGTM_fin_bool(arg8, farg9)
farg10 = arg9%swigdata
call swigc_caf_send(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10)
end subroutine

subroutine caf_sendget(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: arg0
integer(C_SIZE_T), intent(in) :: arg1
integer(C_INT), intent(in) :: arg2
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg3
class(caf_vector_t), intent(in) :: arg4
type(C_PTR), intent(in) :: arg5
integer(C_SIZE_T), intent(in) :: arg6
integer(C_INT), intent(in) :: arg7
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg8
class(caf_vector_t), intent(in) :: arg9
integer(C_INT), intent(in) :: arg10
integer(C_INT), intent(in) :: arg11
logical, intent(in) :: arg12
class(SWIGTYPE_p_int), intent(in) :: arg13
type(C_PTR) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INT) :: farg3 
type(SwigClassWrapper) :: farg4 
type(SwigClassWrapper) :: farg5 
type(C_PTR) :: farg6 
integer(C_SIZE_T) :: farg7 
integer(C_INT) :: farg8 
type(SwigClassWrapper) :: farg9 
type(SwigClassWrapper) :: farg10 
integer(C_INT) :: farg11 
integer(C_INT) :: farg12 
integer(C_INT) :: farg13 
type(SwigClassWrapper) :: farg14 

farg1 = arg0
farg2 = arg1
farg3 = arg2
farg4 = arg3%swigdata
farg5 = arg4%swigdata
farg6 = arg5
farg7 = arg6
farg8 = arg7
farg9 = arg8%swigdata
farg10 = arg9%swigdata
farg11 = arg10
farg12 = arg11
call SWIGTM_fin_bool(arg12, farg13)
farg14 = arg13%swigdata
call swigc_caf_sendget(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9, farg10, farg11, farg12, farg13, farg14)
end subroutine

subroutine co_broadcast(arg0, arg1, arg2, arg3, arg4)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg0
integer(C_INT), intent(in) :: arg1
class(SWIGTYPE_p_int), intent(in) :: arg2
character(len=*), target :: arg3
integer(C_INT), intent(in) :: arg4
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 
type(SwigClassWrapper) :: farg3 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg4_temp 
type(SwigArrayWrapper) :: farg4 
integer(C_INT) :: farg5 

farg1 = arg0%swigdata
farg2 = arg1
farg3 = arg2%swigdata
call SWIGTM_fin_char_Sm_(arg3, farg4, farg4_temp)
farg5 = arg4
call swigc_co_broadcast(farg1, farg2, farg3, farg4, farg5)
end subroutine

subroutine co_max(arg0, arg1, arg2, arg3, arg4, arg5)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg0
integer(C_INT), intent(in) :: arg1
class(SWIGTYPE_p_int), intent(in) :: arg2
character(len=*), target :: arg3
integer(C_INT), intent(in) :: arg4
integer(C_INT), intent(in) :: arg5
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 
type(SwigClassWrapper) :: farg3 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg4_temp 
type(SwigArrayWrapper) :: farg4 
integer(C_INT) :: farg5 
integer(C_INT) :: farg6 

farg1 = arg0%swigdata
farg2 = arg1
farg3 = arg2%swigdata
call SWIGTM_fin_char_Sm_(arg3, farg4, farg4_temp)
farg5 = arg4
farg6 = arg5
call swigc_co_max(farg1, farg2, farg3, farg4, farg5, farg6)
end subroutine

subroutine co_min(arg0, arg1, arg2, arg3, arg4, arg5)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg0
integer(C_INT), intent(in) :: arg1
class(SWIGTYPE_p_int), intent(in) :: arg2
character(len=*), target :: arg3
integer(C_INT), intent(in) :: arg4
integer(C_INT), intent(in) :: arg5
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 
type(SwigClassWrapper) :: farg3 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg4_temp 
type(SwigArrayWrapper) :: farg4 
integer(C_INT) :: farg5 
integer(C_INT) :: farg6 

farg1 = arg0%swigdata
farg2 = arg1
farg3 = arg2%swigdata
call SWIGTM_fin_char_Sm_(arg3, farg4, farg4_temp)
farg5 = arg4
farg6 = arg5
call swigc_co_min(farg1, farg2, farg3, farg4, farg5, farg6)
end subroutine

subroutine co_reduce(arg0, opr, arg2, arg3, arg4, arg5, arg6, arg7)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg0
procedure(SWIGTYPE_f_p_void_p_void__p_void) :: opr
integer(C_INT), intent(in) :: arg2
integer(C_INT), intent(in) :: arg3
class(SWIGTYPE_p_int), intent(in) :: arg4
character(len=*), target :: arg5
integer(C_INT), intent(in) :: arg6
integer(C_INT), intent(in) :: arg7
type(SwigClassWrapper) :: farg1 
type(C_FUNPTR) :: farg2 
integer(C_INT) :: farg3 
integer(C_INT) :: farg4 
type(SwigClassWrapper) :: farg5 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg6_temp 
type(SwigArrayWrapper) :: farg6 
integer(C_INT) :: farg7 
integer(C_INT) :: farg8 

farg1 = arg0%swigdata
farg2 = c_funloc(opr)
farg3 = arg2
farg4 = arg3
farg5 = arg4%swigdata
call SWIGTM_fin_char_Sm_(arg5, farg6, farg6_temp)
farg7 = arg6
farg8 = arg7
call swigc_co_reduce(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8)
end subroutine

subroutine co_sum(arg0, arg1, arg2, arg3, arg4)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg0
integer(C_INT), intent(in) :: arg1
class(SWIGTYPE_p_int), intent(in) :: arg2
character(len=*), target :: arg3
integer(C_INT), intent(in) :: arg4
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 
type(SwigClassWrapper) :: farg3 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg4_temp 
type(SwigArrayWrapper) :: farg4 
integer(C_INT) :: farg5 

farg1 = arg0%swigdata
farg2 = arg1
farg3 = arg2%swigdata
call SWIGTM_fin_char_Sm_(arg3, farg4, farg4_temp)
farg5 = arg4
call swigc_co_sum(farg1, farg2, farg3, farg4, farg5)
end subroutine

subroutine sync_all(arg0, arg1, arg2)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_int), intent(in) :: arg0
character(len=*), target :: arg1
integer(C_INT), intent(in) :: arg2
type(SwigClassWrapper) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 
integer(C_INT) :: farg3 

farg1 = arg0%swigdata
call SWIGTM_fin_char_Sm_(arg1, farg2, farg2_temp)
farg3 = arg2
call swigc_sync_all(farg1, farg2, farg3)
end subroutine

subroutine sync_images(arg0, arg1, arg2, arg3, arg4)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: arg0
class(SWIGTYPE_p_int), intent(in) :: arg1
class(SWIGTYPE_p_int), intent(in) :: arg2
character(len=*), target :: arg3
integer(C_INT), intent(in) :: arg4
integer(C_INT) :: farg1 
type(SwigClassWrapper) :: farg2 
type(SwigClassWrapper) :: farg3 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg4_temp 
type(SwigArrayWrapper) :: farg4 
integer(C_INT) :: farg5 

farg1 = arg0
farg2 = arg1%swigdata
farg3 = arg2%swigdata
call SWIGTM_fin_char_Sm_(arg3, farg4, farg4_temp)
farg5 = arg4
call swigc_sync_images(farg1, farg2, farg3, farg4, farg5)
end subroutine

subroutine sync_memory(arg0, arg1, arg2)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_int), intent(in) :: arg0
character(len=*), target :: arg1
integer(C_INT), intent(in) :: arg2
type(SwigClassWrapper) :: farg1 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg2_temp 
type(SwigArrayWrapper) :: farg2 
integer(C_INT) :: farg3 

farg1 = arg0%swigdata
call SWIGTM_fin_char_Sm_(arg1, farg2, farg2_temp)
farg3 = arg2
call swigc_sync_memory(farg1, farg2, farg3)
end subroutine

subroutine stop_str(arg0, arg1)
use, intrinsic :: ISO_C_BINDING
character(len=*), target :: arg0
integer(C_INT), intent(in) :: arg1
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_temp 
type(SwigArrayWrapper) :: farg1 
integer(C_INT) :: farg2 

call SWIGTM_fin_char_Sm_(arg0, farg1, farg1_temp)
farg2 = arg1
call swigc_stop_str(farg1, farg2)
end subroutine

subroutine stop(arg0)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: arg0
integer(C_INT) :: farg1 

farg1 = arg0
call swigc_stop(farg1)
end subroutine

subroutine error_stop_str(arg0, arg1)
use, intrinsic :: ISO_C_BINDING
character(len=*), target :: arg0
integer(C_INT), intent(in) :: arg1
character(kind=C_CHAR), dimension(:), allocatable, target :: farg1_temp 
type(SwigArrayWrapper) :: farg1 
integer(C_INT) :: farg2 

call SWIGTM_fin_char_Sm_(arg0, farg1, farg1_temp)
farg2 = arg1
call swigc_error_stop_str(farg1, farg2)
end subroutine

subroutine error_stop(arg0)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: arg0
integer(C_INT) :: farg1 

farg1 = arg0
call swigc_error_stop(farg1)
end subroutine

subroutine fail_image()
use, intrinsic :: ISO_C_BINDING

call swigc_fail_image()
end subroutine

subroutine form_team(arg0, arg1, arg2)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: arg0
class(SWIGTYPE_p_p_void), intent(in) :: arg1
integer(C_INT), intent(in) :: arg2
integer(C_INT) :: farg1 
type(SwigClassWrapper) :: farg2 
integer(C_INT) :: farg3 

farg1 = arg0
farg2 = arg1%swigdata
farg3 = arg2
call swigc_form_team(farg1, farg2, farg3)
end subroutine

subroutine change_team(arg0, arg1)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_p_void), intent(in) :: arg0
integer(C_INT), intent(in) :: arg1
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = arg0%swigdata
farg2 = arg1
call swigc_change_team(farg1, farg2)
end subroutine

subroutine end_team(arg0)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_p_void), intent(in) :: arg0
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
call swigc_end_team(farg1)
end subroutine

subroutine sync_team(arg0, arg1)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_p_void), intent(in) :: arg0
integer(C_INT), intent(in) :: arg1
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = arg0%swigdata
farg2 = arg1
call swigc_sync_team(farg1, farg2)
end subroutine

function team_number(arg0) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(SWIGTYPE_p_p_void), intent(in) :: arg0
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = arg0%swigdata
fresult = swigc_team_number(farg1)
swig_result = fresult
end function

function image_status(arg0) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT), intent(in) :: arg0
integer(C_INT) :: fresult 
integer(C_INT) :: farg1 

farg1 = arg0
fresult = swigc_image_status(farg1)
swig_result = fresult
end function

subroutine failed_images(arg0, arg1, arg2)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg0
integer(C_INT), intent(in) :: arg1
class(SWIGTYPE_p_int), intent(in) :: arg2
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = arg0%swigdata
farg2 = arg1
farg3 = arg2%swigdata
call swigc_failed_images(farg1, farg2, farg3)
end subroutine

subroutine stopped_images(arg0, arg1, arg2)
use, intrinsic :: ISO_C_BINDING
class(SWIGTYPE_p_gfc_descriptor_t), intent(in) :: arg0
integer(C_INT), intent(in) :: arg1
class(SWIGTYPE_p_int), intent(in) :: arg2
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = arg0%swigdata
farg2 = arg1
farg3 = arg2%swigdata
call swigc_stopped_images(farg1, farg2, farg3)
end subroutine

subroutine atomic_define(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: arg0
integer(C_SIZE_T), intent(in) :: arg1
integer(C_INT), intent(in) :: arg2
type(C_PTR), intent(in) :: arg3
class(SWIGTYPE_p_int), intent(in) :: arg4
integer(C_INT), intent(in) :: arg5
integer(C_INT), intent(in) :: arg6
type(C_PTR) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INT) :: farg3 
type(C_PTR) :: farg4 
type(SwigClassWrapper) :: farg5 
integer(C_INT) :: farg6 
integer(C_INT) :: farg7 

farg1 = arg0
farg2 = arg1
farg3 = arg2
farg4 = arg3
farg5 = arg4%swigdata
farg6 = arg5
farg7 = arg6
call swigc_atomic_define(farg1, farg2, farg3, farg4, farg5, farg6, farg7)
end subroutine

subroutine atomic_ref(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: arg0
integer(C_SIZE_T), intent(in) :: arg1
integer(C_INT), intent(in) :: arg2
type(C_PTR), intent(in) :: arg3
class(SWIGTYPE_p_int), intent(in) :: arg4
integer(C_INT), intent(in) :: arg5
integer(C_INT), intent(in) :: arg6
type(C_PTR) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INT) :: farg3 
type(C_PTR) :: farg4 
type(SwigClassWrapper) :: farg5 
integer(C_INT) :: farg6 
integer(C_INT) :: farg7 

farg1 = arg0
farg2 = arg1
farg3 = arg2
farg4 = arg3
farg5 = arg4%swigdata
farg6 = arg5
farg7 = arg6
call swigc_atomic_ref(farg1, farg2, farg3, farg4, farg5, farg6, farg7)
end subroutine

subroutine atomic_cas(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: arg0
integer(C_SIZE_T), intent(in) :: arg1
integer(C_INT), intent(in) :: arg2
type(C_PTR), intent(in) :: arg3
type(C_PTR), intent(in) :: arg4
type(C_PTR), intent(in) :: arg5
class(SWIGTYPE_p_int), intent(in) :: arg6
integer(C_INT), intent(in) :: arg7
integer(C_INT), intent(in) :: arg8
type(C_PTR) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INT) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_PTR) :: farg6 
type(SwigClassWrapper) :: farg7 
integer(C_INT) :: farg8 
integer(C_INT) :: farg9 

farg1 = arg0
farg2 = arg1
farg3 = arg2
farg4 = arg3
farg5 = arg4
farg6 = arg5
farg7 = arg6%swigdata
farg8 = arg7
farg9 = arg8
call swigc_atomic_cas(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9)
end subroutine

subroutine atomic_op(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: arg0
type(C_PTR), intent(in) :: arg1
integer(C_SIZE_T), intent(in) :: arg2
integer(C_INT), intent(in) :: arg3
type(C_PTR), intent(in) :: arg4
type(C_PTR), intent(in) :: arg5
class(SWIGTYPE_p_int), intent(in) :: arg6
integer(C_INT), intent(in) :: arg7
integer(C_INT), intent(in) :: arg8
integer(C_INT) :: farg1 
type(C_PTR) :: farg2 
integer(C_SIZE_T) :: farg3 
integer(C_INT) :: farg4 
type(C_PTR) :: farg5 
type(C_PTR) :: farg6 
type(SwigClassWrapper) :: farg7 
integer(C_INT) :: farg8 
integer(C_INT) :: farg9 

farg1 = arg0
farg2 = arg1
farg3 = arg2
farg4 = arg3
farg5 = arg4
farg6 = arg5
farg7 = arg6%swigdata
farg8 = arg7
farg9 = arg8
call swigc_atomic_op(farg1, farg2, farg3, farg4, farg5, farg6, farg7, farg8, farg9)
end subroutine

subroutine lock(arg0, arg1, arg2, arg3, arg4, arg5, arg6)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: arg0
integer(C_SIZE_T), intent(in) :: arg1
integer(C_INT), intent(in) :: arg2
class(SWIGTYPE_p_int), intent(in) :: arg3
class(SWIGTYPE_p_int), intent(in) :: arg4
character(len=*), target :: arg5
integer(C_INT), intent(in) :: arg6
type(C_PTR) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INT) :: farg3 
type(SwigClassWrapper) :: farg4 
type(SwigClassWrapper) :: farg5 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg6_temp 
type(SwigArrayWrapper) :: farg6 
integer(C_INT) :: farg7 

farg1 = arg0
farg2 = arg1
farg3 = arg2
farg4 = arg3%swigdata
farg5 = arg4%swigdata
call SWIGTM_fin_char_Sm_(arg5, farg6, farg6_temp)
farg7 = arg6
call swigc_lock(farg1, farg2, farg3, farg4, farg5, farg6, farg7)
end subroutine

subroutine unlock(arg0, arg1, arg2, arg3, arg4, arg5)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: arg0
integer(C_SIZE_T), intent(in) :: arg1
integer(C_INT), intent(in) :: arg2
class(SWIGTYPE_p_int), intent(in) :: arg3
character(len=*), target :: arg4
integer(C_INT), intent(in) :: arg5
type(C_PTR) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INT) :: farg3 
type(SwigClassWrapper) :: farg4 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg5_temp 
type(SwigArrayWrapper) :: farg5 
integer(C_INT) :: farg6 

farg1 = arg0
farg2 = arg1
farg3 = arg2
farg4 = arg3%swigdata
call SWIGTM_fin_char_Sm_(arg4, farg5, farg5_temp)
farg6 = arg5
call swigc_unlock(farg1, farg2, farg3, farg4, farg5, farg6)
end subroutine

subroutine event_post(arg0, arg1, arg2, arg3, arg4, arg5)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: arg0
integer(C_SIZE_T), intent(in) :: arg1
integer(C_INT), intent(in) :: arg2
class(SWIGTYPE_p_int), intent(in) :: arg3
character(len=*), target :: arg4
integer(C_INT), intent(in) :: arg5
type(C_PTR) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INT) :: farg3 
type(SwigClassWrapper) :: farg4 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg5_temp 
type(SwigArrayWrapper) :: farg5 
integer(C_INT) :: farg6 

farg1 = arg0
farg2 = arg1
farg3 = arg2
farg4 = arg3%swigdata
call SWIGTM_fin_char_Sm_(arg4, farg5, farg5_temp)
farg6 = arg5
call swigc_event_post(farg1, farg2, farg3, farg4, farg5, farg6)
end subroutine

subroutine event_wait(arg0, arg1, arg2, arg3, arg4, arg5)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: arg0
integer(C_SIZE_T), intent(in) :: arg1
integer(C_INT), intent(in) :: arg2
class(SWIGTYPE_p_int), intent(in) :: arg3
character(len=*), target :: arg4
integer(C_INT), intent(in) :: arg5
type(C_PTR) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INT) :: farg3 
type(SwigClassWrapper) :: farg4 
character(kind=C_CHAR), dimension(:), allocatable, target :: farg5_temp 
type(SwigArrayWrapper) :: farg5 
integer(C_INT) :: farg6 

farg1 = arg0
farg2 = arg1
farg3 = arg2
farg4 = arg3%swigdata
call SWIGTM_fin_char_Sm_(arg4, farg5, farg5_temp)
farg6 = arg5
call swigc_event_wait(farg1, farg2, farg3, farg4, farg5, farg6)
end subroutine

subroutine event_query(arg0, arg1, arg2, arg3, arg4)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), intent(in) :: arg0
integer(C_SIZE_T), intent(in) :: arg1
integer(C_INT), intent(in) :: arg2
class(SWIGTYPE_p_int), intent(in) :: arg3
class(SWIGTYPE_p_int), intent(in) :: arg4
type(C_PTR) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_INT) :: farg3 
type(SwigClassWrapper) :: farg4 
type(SwigClassWrapper) :: farg5 

farg1 = arg0
farg2 = arg1
farg3 = arg2
farg4 = arg3%swigdata
farg5 = arg4%swigdata
call swigc_event_query(farg1, farg2, farg3, farg4, farg5)
end subroutine


end module
