/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2+fortran
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGFORTRAN
#define SWIGFORTRAN
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#ifndef SWIGEXTERN
# ifdef __cplusplus
#   define SWIGEXTERN extern
# else
#   define SWIGEXTERN
# endif
#endif


#include <assert.h>
#define SWIG_exception_impl(DECL, CODE, MSG, RETURNNULL) \
 { printf("In " DECL ": " MSG); assert(0); RETURNNULL; }


enum {
    SWIG_MEM_OWN = 0x01,
    SWIG_MEM_RVALUE = 0x02,
};


#define SWIG_check_nonnull(PTR, TYPENAME, FNAME, FUNCNAME, RETURNNULL) \
  if (!(PTR)) { \
    SWIG_exception_impl(FUNCNAME, SWIG_NullReferenceError, \
                        "Cannot pass null " TYPENAME " (class " FNAME ") " \
                        "as a reference", RETURNNULL); \
  }


#include <stdio.h>
#if (defined(_MSC_VER) && (_MSC_VER < 1900)) || defined(__BORLANDC__) || defined(_WATCOM)
# ifndef snprintf
#  define snprintf _snprintf
# endif
#endif


/* Support for the `contract` feature.
 *
 * Note that RETURNNULL is first because it's inserted via a 'Replaceall' in
 * the fortran.cxx file.
 */
#define SWIG_contract_assert(RETURNNULL, EXPR, MSG) \
 if (!(EXPR)) { SWIG_exception_impl("$decl", SWIG_ValueError, MSG, RETURNNULL); } 


#define SWIGVERSION 0x040002 
#define SWIG_VERSION SWIGVERSION


#define SWIG_as_voidptr(a) (void *)((const void *)(a)) 
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a)) 


typedef struct {
    void* cptr;
    int cmemflags;
} SwigClassWrapper;


SWIGINTERN SwigClassWrapper SwigClassWrapper_uninitialized() {
    SwigClassWrapper result;
    result.cptr = NULL;
    result.cmemflags = 0;
    return result;
}


#include <stdlib.h>
#ifdef _MSC_VER
# ifndef strtoull
#  define strtoull _strtoui64
# endif
# ifndef strtoll
#  define strtoll _strtoi64
# endif
#endif


#include <string.h>


SWIGINTERN void SWIG_assign(SwigClassWrapper* self, SwigClassWrapper other) {
  if (self->cptr == NULL) {
    /* LHS is unassigned */
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture pointer from RHS, clear 'moving' flag */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_RVALUE);
    } else {
      /* Become a reference to the other object */
      self->cptr = other.cptr;
      self->cmemflags = other.cmemflags & (~SWIG_MEM_OWN);
    }
  } else if (other.cptr == NULL) {
    /* Replace LHS with a null pointer */
    free(self->cptr);
    *self = SwigClassWrapper_uninitialized();
  } else if (self->cptr == other.cptr) {
    /* Self-assignment: ignore */
  } else {
    if (self->cmemflags & SWIG_MEM_OWN) {
      free(self->cptr);
    }
    self->cptr = other.cptr;
    if (other.cmemflags & SWIG_MEM_RVALUE) {
      /* Capture RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_RVALUE;
    } else {
      /* Point to RHS */
      self->cmemflags = other.cmemflags & ~SWIG_MEM_OWN;
    }
  }
}

typedef union {
  struct {
    void *vector;
    int kind;
  } v;
  struct {
    ptrdiff_t lower_bound, upper_bound, stride;
  } triplet;
} caf_vector_t_u;

typedef struct {
  void *vector;
  int kind;
} caf_vector_t_u_v;

typedef struct {
  ptrdiff_t lower_bound, upper_bound, stride;
} caf_vector_t_u_triplet;


typedef struct {
    void* data;
    size_t size;
} SwigArrayWrapper;


SWIGINTERN SwigArrayWrapper SwigArrayWrapper_uninitialized() {
  SwigArrayWrapper result;
  result.data = NULL;
  result.size = 0;
  return result;
}

SWIGEXPORT int _wrap_STAT_UNLOCKED_get() {
  int fresult ;
  int result;
  
  result = (int)(0);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_STAT_LOCKED_get() {
  int fresult ;
  int result;
  
  result = (int)(1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_STAT_LOCKED_OTHER_IMAGE_get() {
  int fresult ;
  int result;
  
  result = (int)(2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_STAT_DUP_SYNC_IMAGES_get() {
  int fresult ;
  int result;
  
  result = (int)(3);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_STAT_STOPPED_IMAGE_get() {
  int fresult ;
  int result;
  
  result = (int)(6000);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_STAT_FAILED_IMAGE_get() {
  int fresult ;
  int result;
  
  result = (int)(6001);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT void _wrap_caf_teams_list_team_set(SwigClassWrapper *farg1, void const **farg2) {
  struct caf_teams_list *arg1 = (struct caf_teams_list *) 0 ;
  caf_team_t arg2 = (caf_team_t) 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct caf_teams_list *", "caf_teams_list", "caf_teams_list::team", return );
  arg1 = (struct caf_teams_list *)farg1->cptr;
  arg2 = (caf_team_t)(*farg2);
  if (arg1) (arg1)->team = arg2;
}


SWIGEXPORT void * _wrap_caf_teams_list_team_get(SwigClassWrapper *farg1) {
  void * fresult ;
  struct caf_teams_list *arg1 = (struct caf_teams_list *) 0 ;
  caf_team_t result;
  
  SWIG_check_nonnull(farg1->cptr, "struct caf_teams_list *", "caf_teams_list", "caf_teams_list::team", return 0);
  arg1 = (struct caf_teams_list *)farg1->cptr;
  result = (caf_team_t) ((arg1)->team);
  fresult = (caf_team_t)(result);
  return fresult;
}


SWIGEXPORT void _wrap_caf_teams_list_team_id_set(SwigClassWrapper *farg1, int const *farg2) {
  struct caf_teams_list *arg1 = (struct caf_teams_list *) 0 ;
  int arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct caf_teams_list *", "caf_teams_list", "caf_teams_list::team_id", return );
  arg1 = (struct caf_teams_list *)farg1->cptr;
  arg2 = (int)(*farg2);
  if (arg1) (arg1)->team_id = arg2;
}


SWIGEXPORT int _wrap_caf_teams_list_team_id_get(SwigClassWrapper *farg1) {
  int fresult ;
  struct caf_teams_list *arg1 = (struct caf_teams_list *) 0 ;
  int result;
  
  SWIG_check_nonnull(farg1->cptr, "struct caf_teams_list *", "caf_teams_list", "caf_teams_list::team_id", return 0);
  arg1 = (struct caf_teams_list *)farg1->cptr;
  result = (int) ((arg1)->team_id);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT void _wrap_caf_teams_list_prev_set(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct caf_teams_list *arg1 = (struct caf_teams_list *) 0 ;
  struct caf_teams_list *arg2 = (struct caf_teams_list *) 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct caf_teams_list *", "caf_teams_list", "caf_teams_list::prev", return );
  arg1 = (struct caf_teams_list *)farg1->cptr;
  arg2 = (struct caf_teams_list *)farg2->cptr;
  if (arg1) (arg1)->prev = arg2;
}


SWIGEXPORT SwigClassWrapper _wrap_caf_teams_list_prev_get(SwigClassWrapper *farg1) {
  SwigClassWrapper fresult ;
  struct caf_teams_list *arg1 = (struct caf_teams_list *) 0 ;
  struct caf_teams_list *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct caf_teams_list *", "caf_teams_list", "caf_teams_list::prev", return SwigClassWrapper_uninitialized());
  arg1 = (struct caf_teams_list *)farg1->cptr;
  result = (struct caf_teams_list *) ((arg1)->prev);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_caf_teams_list() {
  SwigClassWrapper fresult ;
  struct caf_teams_list *result = 0 ;
  
  result = (struct caf_teams_list *)calloc(1, sizeof(struct caf_teams_list));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_caf_teams_list(SwigClassWrapper *farg1) {
  struct caf_teams_list *arg1 = (struct caf_teams_list *) 0 ;
  
  arg1 = (struct caf_teams_list *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_caf_teams_list_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct caf_teams_list *arg1 = (struct caf_teams_list *) 0 ;
  struct caf_teams_list *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT void _wrap_caf_used_teams_list_team_list_elem_set(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct caf_used_teams_list *arg1 = (struct caf_used_teams_list *) 0 ;
  struct caf_teams_list *arg2 = (struct caf_teams_list *) 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct caf_used_teams_list *", "caf_used_teams_list", "caf_used_teams_list::team_list_elem", return );
  arg1 = (struct caf_used_teams_list *)farg1->cptr;
  arg2 = (struct caf_teams_list *)farg2->cptr;
  if (arg1) (arg1)->team_list_elem = arg2;
}


SWIGEXPORT SwigClassWrapper _wrap_caf_used_teams_list_team_list_elem_get(SwigClassWrapper *farg1) {
  SwigClassWrapper fresult ;
  struct caf_used_teams_list *arg1 = (struct caf_used_teams_list *) 0 ;
  struct caf_teams_list *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct caf_used_teams_list *", "caf_used_teams_list", "caf_used_teams_list::team_list_elem", return SwigClassWrapper_uninitialized());
  arg1 = (struct caf_used_teams_list *)farg1->cptr;
  result = (struct caf_teams_list *) ((arg1)->team_list_elem);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_caf_used_teams_list_prev_set(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct caf_used_teams_list *arg1 = (struct caf_used_teams_list *) 0 ;
  struct caf_used_teams_list *arg2 = (struct caf_used_teams_list *) 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct caf_used_teams_list *", "caf_used_teams_list", "caf_used_teams_list::prev", return );
  arg1 = (struct caf_used_teams_list *)farg1->cptr;
  arg2 = (struct caf_used_teams_list *)farg2->cptr;
  if (arg1) (arg1)->prev = arg2;
}


SWIGEXPORT SwigClassWrapper _wrap_caf_used_teams_list_prev_get(SwigClassWrapper *farg1) {
  SwigClassWrapper fresult ;
  struct caf_used_teams_list *arg1 = (struct caf_used_teams_list *) 0 ;
  struct caf_used_teams_list *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct caf_used_teams_list *", "caf_used_teams_list", "caf_used_teams_list::prev", return SwigClassWrapper_uninitialized());
  arg1 = (struct caf_used_teams_list *)farg1->cptr;
  result = (struct caf_used_teams_list *) ((arg1)->prev);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_caf_used_teams_list() {
  SwigClassWrapper fresult ;
  struct caf_used_teams_list *result = 0 ;
  
  result = (struct caf_used_teams_list *)calloc(1, sizeof(struct caf_used_teams_list));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_caf_used_teams_list(SwigClassWrapper *farg1) {
  struct caf_used_teams_list *arg1 = (struct caf_used_teams_list *) 0 ;
  
  arg1 = (struct caf_used_teams_list *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_caf_used_teams_list_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct caf_used_teams_list *arg1 = (struct caf_used_teams_list *) 0 ;
  struct caf_used_teams_list *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT void _wrap_caf_vector_t_nvec_set(SwigClassWrapper *farg1, size_t const *farg2) {
  struct caf_vector_t *arg1 = (struct caf_vector_t *) 0 ;
  size_t arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct caf_vector_t *", "caf_vector_t", "caf_vector_t::nvec", return );
  arg1 = (struct caf_vector_t *)farg1->cptr;
  arg2 = (size_t)(*farg2);
  if (arg1) (arg1)->nvec = arg2;
}


SWIGEXPORT size_t _wrap_caf_vector_t_nvec_get(SwigClassWrapper *farg1) {
  size_t fresult ;
  struct caf_vector_t *arg1 = (struct caf_vector_t *) 0 ;
  size_t result;
  
  SWIG_check_nonnull(farg1->cptr, "struct caf_vector_t *", "caf_vector_t", "caf_vector_t::nvec", return 0);
  arg1 = (struct caf_vector_t *)farg1->cptr;
  result = (size_t) ((arg1)->nvec);
  fresult = (size_t)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_caf_vector_t_u_get(SwigClassWrapper *farg1) {
  SwigClassWrapper fresult ;
  struct caf_vector_t *arg1 = (struct caf_vector_t *) 0 ;
  caf_vector_t_u *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "struct caf_vector_t *", "caf_vector_t", "caf_vector_t::u", return SwigClassWrapper_uninitialized());
  arg1 = (struct caf_vector_t *)farg1->cptr;
  result = (caf_vector_t_u *)& ((arg1)->u);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_caf_vector_t() {
  SwigClassWrapper fresult ;
  struct caf_vector_t *result = 0 ;
  
  result = (struct caf_vector_t *)calloc(1, sizeof(struct caf_vector_t));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_caf_vector_t(SwigClassWrapper *farg1) {
  struct caf_vector_t *arg1 = (struct caf_vector_t *) 0 ;
  
  arg1 = (struct caf_vector_t *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_caf_vector_t_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  struct caf_vector_t *arg1 = (struct caf_vector_t *) 0 ;
  struct caf_vector_t *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT SwigClassWrapper _wrap_caf_vector_t_u_v_get(SwigClassWrapper *farg1) {
  SwigClassWrapper fresult ;
  caf_vector_t_u *arg1 = (caf_vector_t_u *) 0 ;
  caf_vector_t_u_v *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "caf_vector_t_u *", "caf_vector_t_u", "caf_vector_t::caf_vector_t_u::v", return SwigClassWrapper_uninitialized());
  arg1 = (caf_vector_t_u *)farg1->cptr;
  result = (caf_vector_t_u_v *)& ((arg1)->v);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_caf_vector_t_u_triplet_get(SwigClassWrapper *farg1) {
  SwigClassWrapper fresult ;
  caf_vector_t_u *arg1 = (caf_vector_t_u *) 0 ;
  caf_vector_t_u_triplet *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "caf_vector_t_u *", "caf_vector_t_u", "caf_vector_t::caf_vector_t_u::triplet", return SwigClassWrapper_uninitialized());
  arg1 = (caf_vector_t_u *)farg1->cptr;
  result = (caf_vector_t_u_triplet *)& ((arg1)->triplet);
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (0 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_caf_vector_t_u() {
  SwigClassWrapper fresult ;
  caf_vector_t_u *result = 0 ;
  
  result = (caf_vector_t_u *)calloc(1, sizeof(caf_vector_t_u));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_caf_vector_t_u(SwigClassWrapper *farg1) {
  caf_vector_t_u *arg1 = (caf_vector_t_u *) 0 ;
  
  arg1 = (caf_vector_t_u *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_caf_vector_t_u_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  caf_vector_t_u *arg1 = (caf_vector_t_u *) 0 ;
  caf_vector_t_u *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT void _wrap_caf_vector_t_u_triplet_lower_bound_set(SwigClassWrapper *farg1, long const *farg2) {
  caf_vector_t_u_triplet *arg1 = (caf_vector_t_u_triplet *) 0 ;
  ptrdiff_t arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "caf_vector_t_u_triplet *", "caf_vector_t_u_triplet", "caf_vector_t::caf_vector_t_u::caf_vector_t_u_triplet::lower_bound", return );
  arg1 = (caf_vector_t_u_triplet *)farg1->cptr;
  arg2 = (ptrdiff_t)(*farg2);
  if (arg1) (arg1)->lower_bound = arg2;
}


SWIGEXPORT long _wrap_caf_vector_t_u_triplet_lower_bound_get(SwigClassWrapper *farg1) {
  long fresult ;
  caf_vector_t_u_triplet *arg1 = (caf_vector_t_u_triplet *) 0 ;
  ptrdiff_t result;
  
  SWIG_check_nonnull(farg1->cptr, "caf_vector_t_u_triplet *", "caf_vector_t_u_triplet", "caf_vector_t::caf_vector_t_u::caf_vector_t_u_triplet::lower_bound", return 0);
  arg1 = (caf_vector_t_u_triplet *)farg1->cptr;
  result = (ptrdiff_t) ((arg1)->lower_bound);
  fresult = (ptrdiff_t)(result);
  return fresult;
}


SWIGEXPORT void _wrap_caf_vector_t_u_triplet_upper_bound_set(SwigClassWrapper *farg1, long const *farg2) {
  caf_vector_t_u_triplet *arg1 = (caf_vector_t_u_triplet *) 0 ;
  ptrdiff_t arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "caf_vector_t_u_triplet *", "caf_vector_t_u_triplet", "caf_vector_t::caf_vector_t_u::caf_vector_t_u_triplet::upper_bound", return );
  arg1 = (caf_vector_t_u_triplet *)farg1->cptr;
  arg2 = (ptrdiff_t)(*farg2);
  if (arg1) (arg1)->upper_bound = arg2;
}


SWIGEXPORT long _wrap_caf_vector_t_u_triplet_upper_bound_get(SwigClassWrapper *farg1) {
  long fresult ;
  caf_vector_t_u_triplet *arg1 = (caf_vector_t_u_triplet *) 0 ;
  ptrdiff_t result;
  
  SWIG_check_nonnull(farg1->cptr, "caf_vector_t_u_triplet *", "caf_vector_t_u_triplet", "caf_vector_t::caf_vector_t_u::caf_vector_t_u_triplet::upper_bound", return 0);
  arg1 = (caf_vector_t_u_triplet *)farg1->cptr;
  result = (ptrdiff_t) ((arg1)->upper_bound);
  fresult = (ptrdiff_t)(result);
  return fresult;
}


SWIGEXPORT void _wrap_caf_vector_t_u_triplet_stride_set(SwigClassWrapper *farg1, long const *farg2) {
  caf_vector_t_u_triplet *arg1 = (caf_vector_t_u_triplet *) 0 ;
  ptrdiff_t arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "caf_vector_t_u_triplet *", "caf_vector_t_u_triplet", "caf_vector_t::caf_vector_t_u::caf_vector_t_u_triplet::stride", return );
  arg1 = (caf_vector_t_u_triplet *)farg1->cptr;
  arg2 = (ptrdiff_t)(*farg2);
  if (arg1) (arg1)->stride = arg2;
}


SWIGEXPORT long _wrap_caf_vector_t_u_triplet_stride_get(SwigClassWrapper *farg1) {
  long fresult ;
  caf_vector_t_u_triplet *arg1 = (caf_vector_t_u_triplet *) 0 ;
  ptrdiff_t result;
  
  SWIG_check_nonnull(farg1->cptr, "caf_vector_t_u_triplet *", "caf_vector_t_u_triplet", "caf_vector_t::caf_vector_t_u::caf_vector_t_u_triplet::stride", return 0);
  arg1 = (caf_vector_t_u_triplet *)farg1->cptr;
  result = (ptrdiff_t) ((arg1)->stride);
  fresult = (ptrdiff_t)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_caf_vector_t_u_triplet() {
  SwigClassWrapper fresult ;
  caf_vector_t_u_triplet *result = 0 ;
  
  result = (caf_vector_t_u_triplet *)calloc(1, sizeof(caf_vector_t_u_triplet));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_caf_vector_t_u_triplet(SwigClassWrapper *farg1) {
  caf_vector_t_u_triplet *arg1 = (caf_vector_t_u_triplet *) 0 ;
  
  arg1 = (caf_vector_t_u_triplet *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_caf_vector_t_u_triplet_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  caf_vector_t_u_triplet *arg1 = (caf_vector_t_u_triplet *) 0 ;
  caf_vector_t_u_triplet *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT void _wrap_caf_vector_t_u_v_vector_set(SwigClassWrapper *farg1, void const **farg2) {
  caf_vector_t_u_v *arg1 = (caf_vector_t_u_v *) 0 ;
  void *arg2 = (void *) 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "caf_vector_t_u_v *", "caf_vector_t_u_v", "caf_vector_t::caf_vector_t_u::caf_vector_t_u_v::vector", return );
  arg1 = (caf_vector_t_u_v *)farg1->cptr;
  arg2 = (void *)(*farg2);
  if (arg1) (arg1)->vector = arg2;
}


SWIGEXPORT void * _wrap_caf_vector_t_u_v_vector_get(SwigClassWrapper *farg1) {
  void * fresult ;
  caf_vector_t_u_v *arg1 = (caf_vector_t_u_v *) 0 ;
  void *result = 0 ;
  
  SWIG_check_nonnull(farg1->cptr, "caf_vector_t_u_v *", "caf_vector_t_u_v", "caf_vector_t::caf_vector_t_u::caf_vector_t_u_v::vector", return 0);
  arg1 = (caf_vector_t_u_v *)farg1->cptr;
  result = (void *) ((arg1)->vector);
  fresult = (void *)(result);
  return fresult;
}


SWIGEXPORT void _wrap_caf_vector_t_u_v_kind_set(SwigClassWrapper *farg1, int const *farg2) {
  caf_vector_t_u_v *arg1 = (caf_vector_t_u_v *) 0 ;
  int arg2 ;
  
  SWIG_check_nonnull(farg1->cptr, "caf_vector_t_u_v *", "caf_vector_t_u_v", "caf_vector_t::caf_vector_t_u::caf_vector_t_u_v::kind", return );
  arg1 = (caf_vector_t_u_v *)farg1->cptr;
  arg2 = (int)(*farg2);
  if (arg1) (arg1)->kind = arg2;
}


SWIGEXPORT int _wrap_caf_vector_t_u_v_kind_get(SwigClassWrapper *farg1) {
  int fresult ;
  caf_vector_t_u_v *arg1 = (caf_vector_t_u_v *) 0 ;
  int result;
  
  SWIG_check_nonnull(farg1->cptr, "caf_vector_t_u_v *", "caf_vector_t_u_v", "caf_vector_t::caf_vector_t_u::caf_vector_t_u_v::kind", return 0);
  arg1 = (caf_vector_t_u_v *)farg1->cptr;
  result = (int) ((arg1)->kind);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT SwigClassWrapper _wrap_new_caf_vector_t_u_v() {
  SwigClassWrapper fresult ;
  caf_vector_t_u_v *result = 0 ;
  
  result = (caf_vector_t_u_v *)calloc(1, sizeof(caf_vector_t_u_v));
  fresult.cptr = (void*)result;
  fresult.cmemflags = SWIG_MEM_RVALUE | (1 ? SWIG_MEM_OWN : 0);
  return fresult;
}


SWIGEXPORT void _wrap_delete_caf_vector_t_u_v(SwigClassWrapper *farg1) {
  caf_vector_t_u_v *arg1 = (caf_vector_t_u_v *) 0 ;
  
  arg1 = (caf_vector_t_u_v *)farg1->cptr;
  free((char *) arg1);
}


SWIGEXPORT void _wrap_caf_vector_t_u_v_op_assign__(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  caf_vector_t_u_v *arg1 = (caf_vector_t_u_v *) 0 ;
  caf_vector_t_u_v *arg2 = 0 ;
  
  (void)sizeof(arg1);
  (void)sizeof(arg2);
  SWIG_assign(farg1, *farg2);
  
}


SWIGEXPORT int _wrap_GFC_CAF_BYREF_get() {
  int fresult ;
  int result;
  
  result = (int)((1 << 0));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_GFC_CAF_HIDDENLEN_get() {
  int fresult ;
  int result;
  
  result = (int)((1 << 1));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_GFC_CAF_ARG_VALUE_get() {
  int fresult ;
  int result;
  
  result = (int)((1 << 2));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_GFC_CAF_ARG_DESC_get() {
  int fresult ;
  int result;
  
  result = (int)((1 << 3));
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_is_contiguous(SwigClassWrapper *farg1) {
  int fresult ;
  gfc_descriptor_t *arg1 = (gfc_descriptor_t *) 0 ;
  bool result;
  
  arg1 = (gfc_descriptor_t *)farg1->cptr;
  result = (bool)is_contiguous(arg1);
  fresult = (result ? 1 : 0);
  return fresult;
}


SWIGEXPORT void _wrap_init(SwigClassWrapper *farg1, SwigClassWrapper *farg2) {
  int *arg1 = (int *) 0 ;
  char ***arg2 = (char ***) 0 ;
  
  arg1 = (int *)farg1->cptr;
  arg2 = (char ***)farg2->cptr;
  init(arg1,arg2);
}


SWIGEXPORT void _wrap_finalize() {
  finalize();
}


SWIGEXPORT int _wrap_this_image(int const *farg1) {
  int fresult ;
  int arg1 ;
  int result;
  
  arg1 = (int)(*farg1);
  result = (int)this_image(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_num_images(int const *farg1, int const *farg2) {
  int fresult ;
  int arg1 ;
  int arg2 ;
  int result;
  
  arg1 = (int)(*farg1);
  arg2 = (int)(*farg2);
  result = (int)num_images(arg1,arg2);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT void _wrap_deregister(SwigClassWrapper *farg1, SwigClassWrapper *farg2, SwigArrayWrapper *farg3, int const *farg4) {
  caf_token_t *arg1 = (caf_token_t *) 0 ;
  int *arg2 = (int *) 0 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  
  arg1 = (caf_token_t *)farg1->cptr;
  arg2 = (int *)farg2->cptr;
  arg3 = (char *)(farg3->data);
  arg4 = (int)(*farg4);
  deregister(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void _wrap_caf_get(void const **farg1, size_t const *farg2, int const *farg3, SwigClassWrapper *farg4, SwigClassWrapper *farg5, SwigClassWrapper *farg6, int const *farg7, int const *farg8, int const *farg9, SwigClassWrapper *farg10) {
  caf_token_t arg1 = (caf_token_t) 0 ;
  size_t arg2 ;
  int arg3 ;
  gfc_descriptor_t *arg4 = (gfc_descriptor_t *) 0 ;
  caf_vector_t *arg5 = (caf_vector_t *) 0 ;
  gfc_descriptor_t *arg6 = (gfc_descriptor_t *) 0 ;
  int arg7 ;
  int arg8 ;
  bool arg9 ;
  int *arg10 = (int *) 0 ;
  
  arg1 = (caf_token_t)(*farg1);
  arg2 = (size_t)(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (gfc_descriptor_t *)farg4->cptr;
  arg5 = (caf_vector_t *)farg5->cptr;
  arg6 = (gfc_descriptor_t *)farg6->cptr;
  arg7 = (int)(*farg7);
  arg8 = (int)(*farg8);
  arg9 = (*farg9 ? true : false);
  arg10 = (int *)farg10->cptr;
  caf_get(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
}


SWIGEXPORT void _wrap_caf_send(void const **farg1, size_t const *farg2, int const *farg3, SwigClassWrapper *farg4, SwigClassWrapper *farg5, SwigClassWrapper *farg6, int const *farg7, int const *farg8, int const *farg9, SwigClassWrapper *farg10) {
  caf_token_t arg1 = (caf_token_t) 0 ;
  size_t arg2 ;
  int arg3 ;
  gfc_descriptor_t *arg4 = (gfc_descriptor_t *) 0 ;
  caf_vector_t *arg5 = (caf_vector_t *) 0 ;
  gfc_descriptor_t *arg6 = (gfc_descriptor_t *) 0 ;
  int arg7 ;
  int arg8 ;
  bool arg9 ;
  int *arg10 = (int *) 0 ;
  
  arg1 = (caf_token_t)(*farg1);
  arg2 = (size_t)(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (gfc_descriptor_t *)farg4->cptr;
  arg5 = (caf_vector_t *)farg5->cptr;
  arg6 = (gfc_descriptor_t *)farg6->cptr;
  arg7 = (int)(*farg7);
  arg8 = (int)(*farg8);
  arg9 = (*farg9 ? true : false);
  arg10 = (int *)farg10->cptr;
  caf_send(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
}


SWIGEXPORT void _wrap_caf_sendget(void const **farg1, size_t const *farg2, int const *farg3, SwigClassWrapper *farg4, SwigClassWrapper *farg5, void const **farg6, size_t const *farg7, int const *farg8, SwigClassWrapper *farg9, SwigClassWrapper *farg10, int const *farg11, int const *farg12, int const *farg13, SwigClassWrapper *farg14) {
  caf_token_t arg1 = (caf_token_t) 0 ;
  size_t arg2 ;
  int arg3 ;
  gfc_descriptor_t *arg4 = (gfc_descriptor_t *) 0 ;
  caf_vector_t *arg5 = (caf_vector_t *) 0 ;
  caf_token_t arg6 = (caf_token_t) 0 ;
  size_t arg7 ;
  int arg8 ;
  gfc_descriptor_t *arg9 = (gfc_descriptor_t *) 0 ;
  caf_vector_t *arg10 = (caf_vector_t *) 0 ;
  int arg11 ;
  int arg12 ;
  bool arg13 ;
  int *arg14 = (int *) 0 ;
  
  arg1 = (caf_token_t)(*farg1);
  arg2 = (size_t)(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (gfc_descriptor_t *)farg4->cptr;
  arg5 = (caf_vector_t *)farg5->cptr;
  arg6 = (caf_token_t)(*farg6);
  arg7 = (size_t)(*farg7);
  arg8 = (int)(*farg8);
  arg9 = (gfc_descriptor_t *)farg9->cptr;
  arg10 = (caf_vector_t *)farg10->cptr;
  arg11 = (int)(*farg11);
  arg12 = (int)(*farg12);
  arg13 = (*farg13 ? true : false);
  arg14 = (int *)farg14->cptr;
  caf_sendget(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13,arg14);
}


SWIGEXPORT void _wrap_co_broadcast(SwigClassWrapper *farg1, int const *farg2, SwigClassWrapper *farg3, SwigArrayWrapper *farg4, int const *farg5) {
  gfc_descriptor_t *arg1 = (gfc_descriptor_t *) 0 ;
  int arg2 ;
  int *arg3 = (int *) 0 ;
  char *arg4 = (char *) 0 ;
  charlen_t arg5 ;
  
  arg1 = (gfc_descriptor_t *)farg1->cptr;
  arg2 = (int)(*farg2);
  arg3 = (int *)farg3->cptr;
  arg4 = (char *)(farg4->data);
  arg5 = (charlen_t)(*farg5);
  co_broadcast(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void _wrap_co_max(SwigClassWrapper *farg1, int const *farg2, SwigClassWrapper *farg3, SwigArrayWrapper *farg4, int const *farg5, int const *farg6) {
  gfc_descriptor_t *arg1 = (gfc_descriptor_t *) 0 ;
  int arg2 ;
  int *arg3 = (int *) 0 ;
  char *arg4 = (char *) 0 ;
  int arg5 ;
  charlen_t arg6 ;
  
  arg1 = (gfc_descriptor_t *)farg1->cptr;
  arg2 = (int)(*farg2);
  arg3 = (int *)farg3->cptr;
  arg4 = (char *)(farg4->data);
  arg5 = (int)(*farg5);
  arg6 = (charlen_t)(*farg6);
  co_max(arg1,arg2,arg3,arg4,arg5,arg6);
}


SWIGEXPORT void _wrap_co_min(SwigClassWrapper *farg1, int const *farg2, SwigClassWrapper *farg3, SwigArrayWrapper *farg4, int const *farg5, int const *farg6) {
  gfc_descriptor_t *arg1 = (gfc_descriptor_t *) 0 ;
  int arg2 ;
  int *arg3 = (int *) 0 ;
  char *arg4 = (char *) 0 ;
  int arg5 ;
  charlen_t arg6 ;
  
  arg1 = (gfc_descriptor_t *)farg1->cptr;
  arg2 = (int)(*farg2);
  arg3 = (int *)farg3->cptr;
  arg4 = (char *)(farg4->data);
  arg5 = (int)(*farg5);
  arg6 = (charlen_t)(*farg6);
  co_min(arg1,arg2,arg3,arg4,arg5,arg6);
}


SWIGEXPORT void _wrap_co_reduce(SwigClassWrapper *farg1, void *(*farg2)(void *,void *), int const *farg3, int const *farg4, SwigClassWrapper *farg5, SwigArrayWrapper *farg6, int const *farg7, int const *farg8) {
  gfc_descriptor_t *arg1 = (gfc_descriptor_t *) 0 ;
  void *(*arg2)(void *,void *) = (void *(*)(void *,void *)) 0 ;
  int arg3 ;
  int arg4 ;
  int *arg5 = (int *) 0 ;
  char *arg6 = (char *) 0 ;
  int arg7 ;
  charlen_t arg8 ;
  
  arg1 = (gfc_descriptor_t *)farg1->cptr;
  arg2 = (void *(*)(void *,void *))(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (int)(*farg4);
  arg5 = (int *)farg5->cptr;
  arg6 = (char *)(farg6->data);
  arg7 = (int)(*farg7);
  arg8 = (charlen_t)(*farg8);
  co_reduce(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
}


SWIGEXPORT void _wrap_co_sum(SwigClassWrapper *farg1, int const *farg2, SwigClassWrapper *farg3, SwigArrayWrapper *farg4, int const *farg5) {
  gfc_descriptor_t *arg1 = (gfc_descriptor_t *) 0 ;
  int arg2 ;
  int *arg3 = (int *) 0 ;
  char *arg4 = (char *) 0 ;
  charlen_t arg5 ;
  
  arg1 = (gfc_descriptor_t *)farg1->cptr;
  arg2 = (int)(*farg2);
  arg3 = (int *)farg3->cptr;
  arg4 = (char *)(farg4->data);
  arg5 = (charlen_t)(*farg5);
  co_sum(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void _wrap_sync_all(SwigClassWrapper *farg1, SwigArrayWrapper *farg2, int const *farg3) {
  int *arg1 = (int *) 0 ;
  char *arg2 = (char *) 0 ;
  charlen_t arg3 ;
  
  arg1 = (int *)farg1->cptr;
  arg2 = (char *)(farg2->data);
  arg3 = (charlen_t)(*farg3);
  sync_all(arg1,arg2,arg3);
}


SWIGEXPORT void _wrap_sync_images(int const *farg1, SwigClassWrapper *farg2, SwigClassWrapper *farg3, SwigArrayWrapper *farg4, int const *farg5) {
  int arg1 ;
  int *arg2 ;
  int *arg3 = (int *) 0 ;
  char *arg4 = (char *) 0 ;
  charlen_t arg5 ;
  
  arg1 = (int)(*farg1);
  arg2 = (int *)farg2->cptr;
  arg3 = (int *)farg3->cptr;
  arg4 = (char *)(farg4->data);
  arg5 = (charlen_t)(*farg5);
  sync_images(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void _wrap_sync_memory(SwigClassWrapper *farg1, SwigArrayWrapper *farg2, int const *farg3) {
  int *arg1 = (int *) 0 ;
  char *arg2 = (char *) 0 ;
  charlen_t arg3 ;
  
  arg1 = (int *)farg1->cptr;
  arg2 = (char *)(farg2->data);
  arg3 = (charlen_t)(*farg3);
  sync_memory(arg1,arg2,arg3);
}


SWIGEXPORT void _wrap_stop_str(SwigArrayWrapper *farg1, int const *farg2) {
  char *arg1 = (char *) 0 ;
  charlen_t arg2 ;
  
  arg1 = (char *)(farg1->data);
  arg2 = (charlen_t)(*farg2);
  stop_str((char const *)arg1,arg2);
}


SWIGEXPORT void _wrap_stop(int const *farg1) {
  int arg1 ;
  
  arg1 = (int)(*farg1);
  stop(arg1);
}


SWIGEXPORT void _wrap_error_stop_str(SwigArrayWrapper *farg1, int const *farg2) {
  char *arg1 = (char *) 0 ;
  charlen_t arg2 ;
  
  arg1 = (char *)(farg1->data);
  arg2 = (charlen_t)(*farg2);
  error_stop_str((char const *)arg1,arg2);
}


SWIGEXPORT void _wrap_error_stop(int const *farg1) {
  int arg1 ;
  
  arg1 = (int)(*farg1);
  error_stop(arg1);
}


SWIGEXPORT void _wrap_fail_image() {
  fail_image();
}


SWIGEXPORT void _wrap_form_team(int const *farg1, SwigClassWrapper *farg2, int const *farg3) {
  int arg1 ;
  caf_team_t *arg2 = (caf_team_t *) 0 ;
  int arg3 ;
  
  arg1 = (int)(*farg1);
  arg2 = (caf_team_t *)farg2->cptr;
  arg3 = (int)(*farg3);
  form_team(arg1,arg2,arg3);
}


SWIGEXPORT void _wrap_change_team(SwigClassWrapper *farg1, int const *farg2) {
  caf_team_t *arg1 = (caf_team_t *) 0 ;
  int arg2 ;
  
  arg1 = (caf_team_t *)farg1->cptr;
  arg2 = (int)(*farg2);
  change_team(arg1,arg2);
}


SWIGEXPORT void _wrap_end_team(SwigClassWrapper *farg1) {
  caf_team_t *arg1 = (caf_team_t *) 0 ;
  
  arg1 = (caf_team_t *)farg1->cptr;
  end_team(arg1);
}


SWIGEXPORT void _wrap_sync_team(SwigClassWrapper *farg1, int const *farg2) {
  caf_team_t *arg1 = (caf_team_t *) 0 ;
  int arg2 ;
  
  arg1 = (caf_team_t *)farg1->cptr;
  arg2 = (int)(*farg2);
  sync_team(arg1,arg2);
}


SWIGEXPORT int _wrap_team_number(SwigClassWrapper *farg1) {
  int fresult ;
  caf_team_t *arg1 = (caf_team_t *) 0 ;
  int result;
  
  arg1 = (caf_team_t *)farg1->cptr;
  result = (int)team_number(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT int _wrap_image_status(int const *farg1) {
  int fresult ;
  int arg1 ;
  int result;
  
  arg1 = (int)(*farg1);
  result = (int)image_status(arg1);
  fresult = (int)(result);
  return fresult;
}


SWIGEXPORT void _wrap_failed_images(SwigClassWrapper *farg1, int const *farg2, SwigClassWrapper *farg3) {
  gfc_descriptor_t *arg1 = (gfc_descriptor_t *) 0 ;
  int arg2 ;
  int *arg3 = (int *) 0 ;
  
  arg1 = (gfc_descriptor_t *)farg1->cptr;
  arg2 = (int)(*farg2);
  arg3 = (int *)farg3->cptr;
  failed_images(arg1,arg2,arg3);
}


SWIGEXPORT void _wrap_stopped_images(SwigClassWrapper *farg1, int const *farg2, SwigClassWrapper *farg3) {
  gfc_descriptor_t *arg1 = (gfc_descriptor_t *) 0 ;
  int arg2 ;
  int *arg3 = (int *) 0 ;
  
  arg1 = (gfc_descriptor_t *)farg1->cptr;
  arg2 = (int)(*farg2);
  arg3 = (int *)farg3->cptr;
  stopped_images(arg1,arg2,arg3);
}


SWIGEXPORT void _wrap_atomic_define(void const **farg1, size_t const *farg2, int const *farg3, void const **farg4, SwigClassWrapper *farg5, int const *farg6, int const *farg7) {
  caf_token_t arg1 = (caf_token_t) 0 ;
  size_t arg2 ;
  int arg3 ;
  void *arg4 = (void *) 0 ;
  int *arg5 = (int *) 0 ;
  int arg6 ;
  int arg7 ;
  
  arg1 = (caf_token_t)(*farg1);
  arg2 = (size_t)(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (void *)(*farg4);
  arg5 = (int *)farg5->cptr;
  arg6 = (int)(*farg6);
  arg7 = (int)(*farg7);
  atomic_define(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
}


SWIGEXPORT void _wrap_atomic_ref(void const **farg1, size_t const *farg2, int const *farg3, void const **farg4, SwigClassWrapper *farg5, int const *farg6, int const *farg7) {
  caf_token_t arg1 = (caf_token_t) 0 ;
  size_t arg2 ;
  int arg3 ;
  void *arg4 = (void *) 0 ;
  int *arg5 = (int *) 0 ;
  int arg6 ;
  int arg7 ;
  
  arg1 = (caf_token_t)(*farg1);
  arg2 = (size_t)(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (void *)(*farg4);
  arg5 = (int *)farg5->cptr;
  arg6 = (int)(*farg6);
  arg7 = (int)(*farg7);
  atomic_ref(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
}


SWIGEXPORT void _wrap_atomic_cas(void const **farg1, size_t const *farg2, int const *farg3, void const **farg4, void const **farg5, void const **farg6, SwigClassWrapper *farg7, int const *farg8, int const *farg9) {
  caf_token_t arg1 = (caf_token_t) 0 ;
  size_t arg2 ;
  int arg3 ;
  void *arg4 = (void *) 0 ;
  void *arg5 = (void *) 0 ;
  void *arg6 = (void *) 0 ;
  int *arg7 = (int *) 0 ;
  int arg8 ;
  int arg9 ;
  
  arg1 = (caf_token_t)(*farg1);
  arg2 = (size_t)(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (void *)(*farg4);
  arg5 = (void *)(*farg5);
  arg6 = (void *)(*farg6);
  arg7 = (int *)farg7->cptr;
  arg8 = (int)(*farg8);
  arg9 = (int)(*farg9);
  atomic_cas(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
}


SWIGEXPORT void _wrap_atomic_op(int const *farg1, void const **farg2, size_t const *farg3, int const *farg4, void const **farg5, void const **farg6, SwigClassWrapper *farg7, int const *farg8, int const *farg9) {
  int arg1 ;
  caf_token_t arg2 = (caf_token_t) 0 ;
  size_t arg3 ;
  int arg4 ;
  void *arg5 = (void *) 0 ;
  void *arg6 = (void *) 0 ;
  int *arg7 = (int *) 0 ;
  int arg8 ;
  int arg9 ;
  
  arg1 = (int)(*farg1);
  arg2 = (caf_token_t)(*farg2);
  arg3 = (size_t)(*farg3);
  arg4 = (int)(*farg4);
  arg5 = (void *)(*farg5);
  arg6 = (void *)(*farg6);
  arg7 = (int *)farg7->cptr;
  arg8 = (int)(*farg8);
  arg9 = (int)(*farg9);
  atomic_op(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9);
}


SWIGEXPORT void _wrap_lock(void const **farg1, size_t const *farg2, int const *farg3, SwigClassWrapper *farg4, SwigClassWrapper *farg5, SwigArrayWrapper *farg6, int const *farg7) {
  caf_token_t arg1 = (caf_token_t) 0 ;
  size_t arg2 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  int *arg5 = (int *) 0 ;
  char *arg6 = (char *) 0 ;
  charlen_t arg7 ;
  
  arg1 = (caf_token_t)(*farg1);
  arg2 = (size_t)(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (int *)farg4->cptr;
  arg5 = (int *)farg5->cptr;
  arg6 = (char *)(farg6->data);
  arg7 = (charlen_t)(*farg7);
  lock(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
}


SWIGEXPORT void _wrap_unlock(void const **farg1, size_t const *farg2, int const *farg3, SwigClassWrapper *farg4, SwigArrayWrapper *farg5, int const *farg6) {
  caf_token_t arg1 = (caf_token_t) 0 ;
  size_t arg2 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  char *arg5 = (char *) 0 ;
  charlen_t arg6 ;
  
  arg1 = (caf_token_t)(*farg1);
  arg2 = (size_t)(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (int *)farg4->cptr;
  arg5 = (char *)(farg5->data);
  arg6 = (charlen_t)(*farg6);
  unlock(arg1,arg2,arg3,arg4,arg5,arg6);
}


SWIGEXPORT void _wrap_event_post(void const **farg1, size_t const *farg2, int const *farg3, SwigClassWrapper *farg4, SwigArrayWrapper *farg5, int const *farg6) {
  caf_token_t arg1 = (caf_token_t) 0 ;
  size_t arg2 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  char *arg5 = (char *) 0 ;
  charlen_t arg6 ;
  
  arg1 = (caf_token_t)(*farg1);
  arg2 = (size_t)(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (int *)farg4->cptr;
  arg5 = (char *)(farg5->data);
  arg6 = (charlen_t)(*farg6);
  event_post(arg1,arg2,arg3,arg4,arg5,arg6);
}


SWIGEXPORT void _wrap_event_wait(void const **farg1, size_t const *farg2, int const *farg3, SwigClassWrapper *farg4, SwigArrayWrapper *farg5, int const *farg6) {
  caf_token_t arg1 = (caf_token_t) 0 ;
  size_t arg2 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  char *arg5 = (char *) 0 ;
  charlen_t arg6 ;
  
  arg1 = (caf_token_t)(*farg1);
  arg2 = (size_t)(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (int *)farg4->cptr;
  arg5 = (char *)(farg5->data);
  arg6 = (charlen_t)(*farg6);
  event_wait(arg1,arg2,arg3,arg4,arg5,arg6);
}


SWIGEXPORT void _wrap_event_query(void const **farg1, size_t const *farg2, int const *farg3, SwigClassWrapper *farg4, SwigClassWrapper *farg5) {
  caf_token_t arg1 = (caf_token_t) 0 ;
  size_t arg2 ;
  int arg3 ;
  int *arg4 = (int *) 0 ;
  int *arg5 = (int *) 0 ;
  
  arg1 = (caf_token_t)(*farg1);
  arg2 = (size_t)(*farg2);
  arg3 = (int)(*farg3);
  arg4 = (int *)farg4->cptr;
  arg5 = (int *)farg5->cptr;
  event_query(arg1,arg2,arg3,arg4,arg5);
}



