assert_identical – OpenCoarrays
assert_identical Subroutine
Source File
public subroutine assert_identical(integers)
Arguments
Type Intent Optional Attributes Name
integer, intent(in), dimension(:) :: integers
Called By
Variables
Type Visibility Attributes Name Initial
logical, public :: any_mismatches
integer, public :: i
Call graph
vector_assert calls assert_identical
assert calls vector_assert
output calls assert
set calls assert
assign_field calls assert
sinusoid calls assert
assign_local_field calls assert
construct calls assert
test calls assert, sinusoid
grid_spacing calls assert
oned_message calls assert
main calls test