calibrate_loop – OpenCoarrays
calibrate_loop Function
Source File
function calibrate_loop(usecs) result(cl)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: usecs
Return Value integer(kind=int64)
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=int64), public, parameter :: calibrate_useconds = 100000000
integer(kind=int64), public :: counter
integer(kind=int64), public :: difference
integer(kind=int64), public :: i
integer(kind=int64), public, parameter :: initial_counter = 100000
integer(kind=int64), public, parameter :: initial_ntrial = 1000
integer(kind=int64), public :: loop_time
integer(kind=int64), public :: min_time_usecs
integer(kind=int64), public :: ntrial
real(kind=real64), public, parameter :: preset_tolerance = 1.0_real64
integer(kind=int64), public :: tolerance
integer(kind=int64), public :: total_time
Source Code
function calibrate_loop(usecs) result(cl)
integer(int64) :: cl
integer(int64), intent(in) :: usecs
integer(int64), parameter :: calibrate_useconds = 100000000
!real(real64), parameter :: preset_tolerance = 0.001_real64
real(real64), parameter :: preset_tolerance = 1.0_real64
integer(int64), parameter :: initial_ntrial = 1000
!integer(int64), parameter :: initial_counter = 1000000
integer(int64), parameter :: initial_counter = 100000
   integer( int64) :: counter
   integer( int64) :: min_time_usecs
   integer( int64) :: tolerance
   integer( int64) :: difference
   integer( int64) :: total_time
   integer( int64) :: ntrial
   integer( int64) :: i
   integer( int64) :: loop_time
continue
   counter = initial_counter
   !write(*,*) 'Counter after initial counter',counter
!  if usecs / granularity is less than 1/preset_tolerance then use zero
   tolerance = int( real( usecs, real64) * preset_tolerance, int64)
   total_time = 0
   trials: do
      ntrial = initial_ntrial
      min_time_usecs = huge( 0_int64)
      get_min: do i = 1, ntrial
         loop_time = loop( counter)
     !write(*,*) 'loop_time',loop_time
         min_time_usecs = min( min_time_usecs, loop_time)
      end do get_min
!  keep an estimate of total calibration time
      total_time = total_time + min_time_usecs * ntrial
      counter = int( real( counter, real64) * real( usecs, real64) / real( min_time_usecs, real64), int64)
      !write(*,*) 'Counter after assignment',counter
      difference = abs( min_time_usecs - usecs)
      if( difference <= tolerance .or. total_time >= calibrate_useconds ) exit trials
   end do trials
   cl = counter
   write( unit= output_unit, fmt= '( a, i2, a, i10, a, i10, a, i10, a, i10)' ) "#rank= ", rank, &
                                                                           " count= ", counter, " time= ", min_time_usecs, &
                                                                           " difference= ", difference, " tolerance= ", tolerance
   time_out: if( total_time > calibrate_useconds )then
      write( unit= output_unit, fmt= '( a, i2, a, f10.4, a, f10.4, a, f10.4, a, i0)' ) "PSNAP: WARNING rank ", rank, &
                                                                  " didn't converge in 10 seconds tolerance = ",  &
                                                                  real( difference) / real( usecs), &
                                                                  " should be ", preset_tolerance, " approx ", &
                                                                  preset_tolerance * 100.0, " percent, granularity= ", usecs
   end if time_out
return
end function calibrate_loop
Call graph
calibrate_loop calls loop
loop calls elapsed_time, from_lower_half, stop_timer, sending_half, start_timer, images, to_upper_half
psnap calls calibrate_loop