co_reduce_c_int – OpenCoarrays
co_reduce_c_int Subroutine
Source File
private subroutine co_reduce_c_int(a, opr, result_image, stat, errmsg)
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(inout), volatile, contiguous :: a(..)
procedure(c_int_operator) :: opr
integer(kind=c_int), intent(in), optional :: result_image
integer(kind=c_int), intent(out), optional volatile :: stat
character(kind=c_char), intent(out), optional volatile :: errmsg(*)
Calls
Called By
Variables
Type Visibility Attributes Name Initial
type(gfc_descriptor_t), public, target :: a_descriptor
integer(kind=c_int), public, volatile :: a_len_unused
integer(kind=c_int), public, parameter :: default_result_image = 0
integer(kind=c_int), public, volatile :: errmsg_len
integer(kind=c_int), public, volatile :: opr_flags_unused
integer(kind=c_int), public :: result_image_
Call graph
co_reduce_c_int calls gfc_descriptor, opencoarrays_co_reduce
gfc_descriptor calls gfc_descriptor_c_int, gfc_descriptor_logical, gfc_descriptor_c_double
gfc_descriptor_c_int calls my_dtype
gfc_descriptor_logical calls my_dtype
gfc_descriptor_c_double calls my_dtype
co_reduce calls co_reduce_c_int