construct – OpenCoarrays
construct Subroutine
Source File
private subroutine construct(this, initial, num_grid_pts)
Arguments
Type Intent Optional Attributes Name
class(periodic_2nd_order), intent(inout) :: this
procedure(initial_field), intent(in), pointer :: initial
integer(kind=ikind), intent(in) :: num_grid_pts
Calls
Variables
Type Visibility Attributes Name Initial
integer, public :: i
double precision, public :: left
double precision, public :: left_sub
double precision, public :: right
double precision, public :: right_sub
Functions
pure function grid()
Arguments
None
Return Value real(kind=rkind), dimension(:),allocatable
Call graph
construct calls grid, assert, error_message
assert calls scalar_assert, vector_assert
error_message calls new_message
vector_assert calls assert_identical