copy3 – OpenCoarrays
copy3 Subroutine
Source File
public subroutine copy3(A, B, n1, sA1, sB1, n2, sA2, sB2, n3, sA3, sB3)
Arguments
Type Intent Optional Attributes Name
complex, intent(in) :: A(0:*)
complex, intent(out) :: B(0:*)
integer(kind=int64), intent(in) :: n1
integer(kind=int64), intent(in) :: sA1
integer(kind=int64), intent(in) :: sB1
integer(kind=int64), intent(in) :: n2
integer(kind=int64), intent(in) :: sA2
integer(kind=int64), intent(in) :: sB2
integer(kind=int64), intent(in) :: n3
integer(kind=int64), intent(in) :: sA3
integer(kind=int64), intent(in) :: sB3
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=int64), public :: i
integer(kind=int64), public :: j
integer(kind=int64), public :: k
Source Code
subroutine copy3(A,B, n1, sA1, sB1, n2, sA2, sB2, n3, sA3, sB3)
  implicit none
  complex, intent(in)  :: A(0:*)
  complex, intent(out) :: B(0:*)
  integer(int64), intent(in) :: n1, sA1, sB1
  integer(int64), intent(in) :: n2, sA2, sB2
  integer(int64), intent(in) :: n3, sA3, sB3
  integer(int64) i,j,k
  do k=0,n3-1
     do j=0,n2-1
        do i=0,n1-1
           B(i*sB1+j*sB2+k*sB3) = A(i*sA1+j*sA2+k*sA3)
        end do
     end do
  end do
end subroutine copy3
Call graph
transpose_x_y calls copy3
transpose_y_x calls copy3
coarray_distributed_transpose calls transpose_x_y, transpose_y_x
solve_navier_stokes calls transpose_y_x, transpose_x_y