get_c_int – OpenCoarrays
get_c_int Subroutine
Source File
private subroutine get_c_int(src, dest, image_index_, offset, mrt)
Uses:
iso_fortran_env
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in), target, contiguous :: src(..)
integer(kind=c_int), intent(out), target, contiguous, volatile :: dest(..)
integer(kind=c_int), intent(in) :: image_index_
integer(kind=c_ptrdiff_t), intent(in) :: offset
logical(kind=c_bool), intent(in) :: mrt
Calls
Variables
Type Visibility Attributes Name Initial
type(gfc_descriptor_t), public, target, volatile :: dest_descriptor
type(gfc_descriptor_t), public, target :: src_descriptor
type(caf_vector_t), public :: src_vector_unused
type(c_ptr), public :: token
Call graph
get_c_int calls error_stop, opencoarrays_get, gfc_descriptor
error_stop calls opencoarrays_error_stop
gfc_descriptor calls gfc_descriptor_c_int, gfc_descriptor_logical, gfc_descriptor_c_double
gfc_descriptor_c_int calls my_dtype
gfc_descriptor_logical calls my_dtype
gfc_descriptor_c_double calls my_dtype