get_keyword_values – OpenCoarrays
get_keyword_values Function
Source File
public function get_keyword_values(keys, default_values) result(actual_values)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in), dimension(:) :: keys
character(len=*), intent(in), dimension(:) :: default_values
Return Value character(len=:), dimension(:),allocatable
Calls
Variables
Type Visibility Attributes Name Initial
character(len=1), public, parameter :: divider = "="
integer, public :: divider_position
integer, public :: error_flag
integer, public :: i
integer, public :: j
character(len=:), public, allocatable :: key_value_pair
character(len=:), public, allocatable :: trimmed_argument
character(len=:), public, allocatable :: trimmed_value
Functions
function max_argument_length()
Arguments
None
Return Value integer
Subroutines
subroutine check(flag)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: flag
Call graph
get_keyword_values calls assert, max_argument_length, check