gfc_descriptor_c_int – OpenCoarrays
gfc_descriptor_c_int Function
Source File
private function gfc_descriptor_c_int(a) result(a_descriptor)
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(in), target, contiguous :: a(..)
Return Value type(gfc_descriptor_t)
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=c_int), public :: i
integer(kind=c_int), public, parameter :: scalar_offset = -1
integer(kind=c_int), public, parameter :: unit_stride = 1
Call graph
gfc_descriptor_c_int calls my_dtype
gfc_descriptor calls gfc_descriptor_c_int
co_max_c_int calls gfc_descriptor
co_sum_c_double calls gfc_descriptor
co_broadcast_c_double calls gfc_descriptor
co_reduce_c_int calls gfc_descriptor
co_min_c_double calls gfc_descriptor
co_reduce_logical calls gfc_descriptor
co_reduce_c_double calls gfc_descriptor
co_sum_c_int calls gfc_descriptor
co_min_c_int calls gfc_descriptor
co_max_c_double calls gfc_descriptor
co_broadcast_c_int calls gfc_descriptor
get_c_int calls gfc_descriptor
co_max calls co_max_c_int, co_max_c_double
co_sum calls co_sum_c_double, co_sum_c_int
co_broadcast calls co_broadcast_c_double, co_broadcast_c_int, co_broadcast_c_char
co_reduce calls co_reduce_c_int, co_reduce_logical, co_reduce_c_double
co_min calls co_min_c_double, co_min_c_int
co_broadcast_c_char calls co_broadcast_c_int