solve_navier_stokes – OpenCoarrays
solve_navier_stokes Subroutine
Source File
subroutine solve_navier_stokes()
Uses:
run_size
Arguments
None
Description
****************)
****************)
****************)
*****************)
***************)
***************)
*****************)
****************)
****************)
****************)
****************)
****************)
****************)
Calls
Variables
Type Visibility Attributes Name Initial
complex, public, allocatable :: bufr_X_Y(:,:,:,:)
complex, public, allocatable :: bufr_Y_X(:,:,:,:)
real, public :: k1(nx/2)
real, public :: k2(ny)
real, public :: k3(nz)
real, public :: kx(nx/2)
real, public :: ky(nx/2,ny)
real, public :: ky_(nx/2,ny)
real, public :: kz(nz)
real, public :: mk1(nx/2)
real, public :: mk2(ny)
real, public :: mk3(nz)
integer(kind=int64), public :: nshells
integer(kind=int64), public :: oflag
integer(kind=int64), public :: rflag
integer(kind=int64), public :: rkstep
integer(kind=int64), public :: step
integer(kind=int64), public :: stop
complex, public :: sx(nx/2,3)
complex, public :: sy(ny,3)
complex, public :: sz(nz,3)
integer(kind=int64), public :: trigx
integer(kind=int64), public :: trigxy
integer(kind=int64), public :: trigy
integer(kind=int64), public :: trigz
complex, public, allocatable :: u(:,:,:,:)[:]
complex, public, allocatable :: un(:,:,:,:)
complex, public, allocatable :: ur(:,:,:,:)[:]
Interfaces
interface
function WALLTIME() bind(C, name = "WALLTIME")
Arguments
None
Return Value real(kind=real64)
interface
subroutine cfft(len, lot, data, inc, jmp, ctrig, isign) bind(C)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in), value :: len
integer(kind=int64), intent(in), value :: lot
complex, intent(in), dimension(0:0) :: data
integer(kind=int64), intent(in), value :: inc
integer(kind=int64), intent(in), value :: jmp
integer(kind=int64), intent(in), value :: ctrig
integer(kind=int64), intent(in), value :: isign
interface
function ctrig(len) bind(C)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in), value :: len
Return Value integer(kind=int64)
interface
subroutine rfft(len, lot, data, inc, jmp, rtrig, isign) bind(C)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in), value :: len
integer(kind=int64), intent(in), value :: lot
complex, intent(in), dimension(0:0) :: data
integer(kind=int64), intent(in), value :: inc
integer(kind=int64), intent(in), value :: jmp
integer(kind=int64), intent(in), value :: rtrig
integer(kind=int64), intent(in), value :: isign
interface
function rtrig(len) bind(C)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in), value :: len
Return Value integer(kind=int64)
Subroutines
subroutine advance()
Arguments
None
subroutine copy_n_s()
Arguments
None
subroutine copy_s_n()
Arguments
None
subroutine define_field()
Arguments
None
subroutine define_kspace()
Arguments
None
subroutine define_shifts()
Arguments
None
subroutine define_step()
Arguments
None
subroutine enforce_conjugate_symmetry()
Arguments
None
subroutine phase1()
Arguments
None
subroutine phase2()
Arguments
None
subroutine phase3()
Arguments
None
subroutine pressure()
Arguments
None
subroutine remesh()
Arguments
None
subroutine spectra()
Arguments
None
subroutine transpose_X_Y()
Arguments
None
subroutine transpose_Y_X()
Arguments
None
Source Code
        subroutine solve_navier_stokes
        end subroutine solve_navier_stokes
Call graph
solve_navier_stokes calls define_field, copy_s_n, enforce_conjugate_symmetry, pressure, global_times, copy_n_s, advance, define_shifts, phase3, transpose_y_x, rtrig, ctrig, phase2, phase1, define_step, define_kspace, transpose_x_y, walltime
init_random_seed calls lcg