warmup_loop – OpenCoarrays
warmup_loop Subroutine
Source File
subroutine warmup_loop(wa)
Arguments
Type Intent Optional Attributes Name
integer(kind=int64), intent(in) :: wa
Calls
Called By
Variables
Type Visibility Attributes Name Initial
integer(kind=int64), public, parameter :: counter = 10000
integer, public :: i
integer(kind=int64), public :: loop_time
integer(kind=int64), public :: min_time_usecs
Source Code
subroutine warmup_loop(wa)
integer(int64), intent(in) :: wa
!integer(int64), parameter :: counter = 1000000
integer(int64), parameter :: counter = 10000
   integer( int64) :: min_time_usecs
   integer( int64) :: loop_time
   integer :: i
continue
   min_time_usecs = huge( 0_int64)
   reloop: do i = 1, wa
      loop_time = loop( counter)
      min_time_usecs = min( loop_time, min_time_usecs)
   end do reloop
return
end subroutine warmup_loop
Call graph
warmup_loop calls loop
loop calls from_lower_half, images, sending_half, stop_timer, elapsed_time, to_upper_half, start_timer
psnap calls warmup_loop