co_reduce – OpenCoarrays
co_reduce Interface
Source File
public interface co_reduce
Calls
Module Procedures
private subroutine co_reduce_c_int(a, opr, result_image, stat, errmsg)
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(inout), volatile, contiguous :: a(..)
procedure(c_int_operator) :: opr
integer(kind=c_int), intent(in), optional :: result_image
integer(kind=c_int), intent(out), optional volatile :: stat
character(kind=c_char), intent(out), optional volatile :: errmsg(*)
private subroutine co_reduce_c_double(a, opr, result_image, stat, errmsg)
Arguments
Type Intent Optional Attributes Name
real(kind=c_double), intent(inout), volatile, contiguous :: a(..)
procedure(c_double_operator) :: opr
integer(kind=c_int), intent(in), optional :: result_image
integer(kind=c_int), intent(out), optional volatile :: stat
character(kind=c_char), intent(out), optional volatile :: errmsg(*)
private subroutine co_reduce_logical(a, opr, result_image, stat, errmsg)
Arguments
Type Intent Optional Attributes Name
logical, intent(inout), volatile, contiguous :: a(..)
procedure(logical_operator) :: opr
integer(kind=c_int), intent(in), optional :: result_image
integer(kind=c_int), intent(out), optional volatile :: stat
character(kind=c_char), intent(out), optional volatile :: errmsg(*)
Call graph
co_reduce calls co_reduce_logical, co_reduce_c_int, co_reduce_c_double
co_reduce_logical calls gfc_descriptor, opencoarrays_co_reduce
co_reduce_c_int calls gfc_descriptor, opencoarrays_co_reduce
co_reduce_c_double calls gfc_descriptor, opencoarrays_co_reduce
gfc_descriptor calls gfc_descriptor_c_int, gfc_descriptor_logical, gfc_descriptor_c_double
gfc_descriptor_c_int calls my_dtype
gfc_descriptor_logical calls my_dtype
gfc_descriptor_c_double calls my_dtype