co_sum – OpenCoarrays
co_sum Interface
Source File
public interface co_sum
Calls
Module Procedures
private subroutine co_sum_c_int(a, result_image, stat, errmsg)
Arguments
Type Intent Optional Attributes Name
integer(kind=c_int), intent(inout), volatile, target, contiguous :: a(..)
integer(kind=c_int), intent(in), optional :: result_image
integer(kind=c_int), intent(out), optional :: stat
character(kind=1,len=*), intent(out), optional :: errmsg
private subroutine co_sum_c_double(a, result_image, stat, errmsg)
Arguments
Type Intent Optional Attributes Name
real(kind=c_double), intent(inout), volatile, target, contiguous :: a(..)
integer(kind=c_int), intent(in), optional :: result_image
integer(kind=c_int), intent(out), optional :: stat
character(kind=1,len=*), intent(out), optional :: errmsg
Call graph
co_sum calls co_sum_c_int, co_sum_c_double
co_sum_c_int calls gfc_descriptor, opencoarrays_co_sum
co_sum_c_double calls gfc_descriptor, opencoarrays_co_sum
gfc_descriptor calls gfc_descriptor_c_int, gfc_descriptor_logical, gfc_descriptor_c_double
gfc_descriptor_c_int calls my_dtype
gfc_descriptor_logical calls my_dtype
gfc_descriptor_c_double calls my_dtype