elapsed_time – OpenCoarrays
elapsed_time Interface
Source File
interface
Called By
function elapsed_time() result(res) bind(c,name="elapsed_time")
Uses:
iso_c_binding
Arguments
None
Return Value integer(kind=c_int)
Call graph
loop calls elapsed_time
psnap calls loop, calibrate_loop, warmup_loop
calibrate_loop calls loop
warmup_loop calls loop