error_message – OpenCoarrays
error_message Interface
Source File
public interface error_message
@cond Interface
Calls
Called By
Module Procedures
private function new_message(message, message_data)
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: message
class(*), intent(in), optional :: message_data
Return Value type(error_message)
Call graph
error_message calls new_message
output calls error_message
set calls error_message
assign_field calls error_message
sinusoid calls error_message
assign_local_field calls error_message
construct calls error_message
test calls error_message, sinusoid
grid_spacing calls error_message
oned_message calls error_message
main calls test