opencoarrays_co_broadcast – OpenCoarrays
opencoarrays_co_broadcast Interface
Source File
interface
Called By
private subroutine opencoarrays_co_broadcast(a, source_image, stat, errmsg, errmsg_len) bind(C,name="0")
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: a
integer(kind=c_int), intent(in), value :: source_image
integer(kind=c_int), intent(out), optional :: stat
character(kind=c_char), intent(out), optional :: errmsg(*)
integer(kind=c_int), intent(in), value :: errmsg_len
Call graph
co_broadcast_c_int calls opencoarrays_co_broadcast
co_broadcast_c_double calls opencoarrays_co_broadcast
co_broadcast_c_char calls co_broadcast_c_int
co_broadcast calls co_broadcast_c_int, co_broadcast_c_double, co_broadcast_c_char