#!/bin/bash
#
# Coarray Fortran (CAF) Compiler Wrapper
#
# Copyright (c) 2015, Sourcery, Inc.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the Sourcery, Inc., nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL SOURCERY, INC., BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. 
 

# This script invokes the chosen Fortran compiler with the received command-line
# arguments.  Current assumptions:
#    1. Fortran source-file name appears as the first argument and has the extension
#       .f90, .F90, .f, or .F.
#    2. The environment variable "FC" is either empty or points to a Fortran compiler 
#       that is capable of compiling and linking the program.
#    3. If "FC" is empty, a default value of "mpif90" is used. 
#    4. This script must be invoked in the directory where "caf-awareness.sh" is located. 
#
# TO DO: 
#    1. Relax the above assumptions.
#    2. Pre-process the Fortran source to translate CAF statements into OpenCoarrays 
#       calls.
# 

source caf-awareness.sh

# Default to "mpif90" Fortran compiler if environment variable FC has zero length:
if [ -z "$FC" ]; then
   FC=mpif90
fi

if [ "$caf_compiler" = "true" ]; then
  # Pass execution permanently to the compiler along with all command-line arguments:
  exec $FC "$@"
else
  echo "CAF: Pre-processing of CAF programs for non-CAF compilers not yet implemented."
  echo "     Attempting to compile raw source."
  # Verify that a file with the .f90, .F90, .f, or .F extension is the first argument:
  src_extension=`echo "$1" | cut -f2 -d'.'`
  if [[ $src_extension == 'f90' || $src_extension == 'F90' || $src_extension == 'f' || $src_extension == 'F' ]]; then
    # Pass execution permanently to the compiler along with all command-line arguments:
    exec $FC "$@"
  else
    echo "CAF: The first argument must contain a .f90, .F90, .f, or .F file extension."
  fi
fi
