include_path=./include-files
library_path=./library
executable= burgers_static_caf
#Cray compiler command
cray=ftn -ew -h caf
#Intel compiler command
intel=ifort -Bdynamic -coarray=shared -standard-semantics -O3 -coarray-num-images=4

# TAU compiler command 
tau_intel=tauf90 -tau:serial,pdt  -Bdynamic -coarray=shared -standard-semantics -O3 -coarray-num-images=4 -DTAU=1

#GNU compiler command
gnu=gfortran -fcoarray=single
#Intel Compiler on ACISS
tau_aciss=tau_f90.sh -v -Bdynamic -coarray=shared -standard-semantics -O3
#Cray Compiler on Hopper
tau_hopper=tau_f90.sh -optCompInst -ew -h caf -g
compile=$(intel)
compile=$(tau_intel)
# Please uncomment the # to use TAU

OPTS=
objects = local_field.o global_field.o kind_parameters.o co_object_interface.o object_interface.o math_constants.o ForTrilinos_assertion_utility.o ForTrilinos_error.o

$(executable): main.o $(objects) Makefile
	$(compile) $(OPTS)  main.o $(objects) -o $(executable) 

main.o: main.F90 $(objects) Makefile
	$(compile) $(OPTS) -c main.F90

global_field.o: global_field.F90 local_field.o kind_parameters.o co_object_interface.o ForTrilinos_assertion_utility.o ForTrilinos_error.o preprocessor_definitions Makefile
	$(compile) $(OPTS) -c global_field.F90

local_field.o: local_field.F90 kind_parameters.o math_constants.o object_interface.o ForTrilinos_assertion_utility.o ForTrilinos_error.o Makefile
	$(compile) $(OPTS) -c local_field.F90

kind_parameters.o: kind_parameters.F90 Makefile
	$(compile) $(OPTS) -c kind_parameters.F90

math_constants.o: math_constants.F90 kind_parameters.o Makefile
	cp $(include_path)/intel_capabilities.txt compiler_capabilities.txt
	cp $(include_path)/intel_capabilities.txt $(library_path)/compiler_capabilities.txt
	$(compile) $(OPTS) -c math_constants.F90

object_interface.o: $(library_path)/object_interface.F90 preprocessor_definitions Makefile
	$(compile) $(OPTS) -c $(library_path)/object_interface.F90

co_object_interface.o: $(library_path)/co_object_interface.F90 Makefile
	$(compile) $(OPTS) -c $(library_path)/co_object_interface.F90

ForTrilinos_assertion_utility.o: $(library_path)/ForTrilinos_assertion_utility.F90 preprocessor_definitions Makefile 
	$(compile) $(OPTS) -c $(library_path)/ForTrilinos_assertion_utility.F90

ForTrilinos_error.o: $(library_path)/ForTrilinos_error.F90 Makefile
	$(compile) $(OPTS) -c $(library_path)/ForTrilinos_error.F90

.PHONY : clean
clean :
	-rm -f  *.o *.mod $(executable) core fort.* $(library_path)/compiler_capabilities.txt profile* MULT* *.trc *.edf

preprocessor_definitions: 
ifeq ($(compile),$(gnu))
	cp $(include_path)/gfortran_capabilities.txt compiler_capabilities.txt
	cp $(include_path)/gfortran_capabilities.txt $(library_path)/compiler_capabilities.txt
else
  ifeq ($(compile),$(intel))
	cp $(include_path)/intel_capabilities.txt compiler_capabilities.txt
	cp $(include_path)/intel_capabilities.txt $(library_path)/compiler_capabilities.txt
  else
      ifeq ($(compile),$(cray))
	cp $(include_path)/cray_capabilities.txt compiler_capabilities.txt
	cp $(include_path)/cray_capabilities.txt $(library_path)/compiler_capabilities.txt
      endif
  endif
endif

ifeq ($(compile),$(tau_gnu))
	cp $(include_path)/gfortran_capabilities.txt compiler_capabilities.txt
	cp $(include_path)/gfortran_capabilities.txt $(library_path)/compiler_capabilities.txt
else
  ifeq ($(compile),$(tau_intel))
	cp $(include_path)/intel_capabilities.txt compiler_capabilities.txt
	cp $(include_path)/intel_capabilities.txt $(library_path)/compiler_capabilities.txt
  else
      ifeq ($(compile),$(tau_cray))
	cp $(include_path)/cray_capabilities.txt compiler_capabilities.txt
	cp $(include_path)/cray_capabilities.txt $(library_path)/compiler_capabilities.txt
      endif
  endif
endif
