main – OpenCoarrays
main Program
Source File
Uses:
iso_fortran_env
ieee_arithmetic
global_field_module
ForTrilinos_assertion_utility
Calls
Variables
Type Attributes Name Initial
real(kind=real64) :: dt
real(kind=real64) :: dx
real(kind=real64), parameter :: final_time = 0.6_real64
type(global_field) :: half_uu
procedure(initial_condition), pointer :: initial_u => ten_sin
integer, parameter :: nodes = 16
real(kind=real64), parameter :: nu = 1.
real(kind=real64), parameter :: safety_factor = 0.1_real64
real(kind=real64) :: time = 0.
real(kind=real64), parameter :: tolerance = 1.E-3_real64
type(global_field) :: u
type(global_field) :: u_half
Functions
pure function diffusion_stability_limit(diffusivity, delta_x, order_of_accuracy) result(stable_time_step)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: diffusivity
real(kind=real64), intent(in) :: delta_x
integer, intent(in) :: order_of_accuracy
Return Value real(kind=real64)
function sinusoid(u_solution) result(is_sinusoid)
Arguments
Type Intent Optional Attributes Name
type(global_field), intent(in) :: u_solution
Return Value logical
pure function ten_sin(x) result(ten_sin_x)
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in) :: x
Return Value real(kind=real64)
Subroutines
subroutine test(burgers_solution)
Arguments
Type Intent Optional Attributes Name
type(global_field), intent(in) :: burgers_solution
Call graph
main calls diffusion_stability_limit, test
test calls sinusoid, assert, error_message
sinusoid calls assert, error_message
assert calls scalar_assert, vector_assert
error_message calls new_message
vector_assert calls assert_identical