mpi_distributed_transpose – OpenCoarrays
mpi_distributed_transpose Program
Source File
Uses:
mpi_run_size
****************)
Calls
Variables
Type Attributes Name Initial
integer, parameter :: MPI_2DOUBLE_PRECISION = 1275072547
integer, parameter :: MPI_2INT = 1275070486
integer, parameter :: MPI_2INTEGER = 1275070496
integer, parameter :: MPI_2REAL = 1275070497
integer, parameter :: MPI_ADDRESS_KIND = 8
integer, parameter :: MPI_AINT = 1275070531
integer, parameter :: MPI_ANY_SOURCE = -2
integer, parameter :: MPI_ANY_TAG = -1
integer, parameter :: MPI_APPNUM = 1681915918
character :: MPI_ARGVS_NULL(1,1)
character :: MPI_ARGV_NULL(1)
logical :: MPI_ASYNC_PROTECTS_NONBLOCKING
integer, parameter :: MPI_BAND = 1476395014
integer, parameter :: MPI_BOR = 1476395016
integer :: MPI_BOTTOM
integer, parameter :: MPI_BSEND_OVERHEAD = 96
integer, parameter :: MPI_BXOR = 1476395018
integer, parameter :: MPI_BYTE = 1275068685
integer, parameter :: MPI_CART = 2
integer, parameter :: MPI_CHAR = 1275068673
integer, parameter :: MPI_CHARACTER = 1275068698
integer, parameter :: MPI_COMBINER_CONTIGUOUS = 3
integer, parameter :: MPI_COMBINER_DARRAY = 14
integer, parameter :: MPI_COMBINER_DUP = 2
integer, parameter :: MPI_COMBINER_F90_COMPLEX = 16
integer, parameter :: MPI_COMBINER_F90_INTEGER = 17
integer, parameter :: MPI_COMBINER_F90_REAL = 15
integer, parameter :: MPI_COMBINER_HINDEXED = 9
integer, parameter :: MPI_COMBINER_HINDEXED_BLOCK = 19
integer, parameter :: MPI_COMBINER_HINDEXED_INTEGER = 8
integer, parameter :: MPI_COMBINER_HVECTOR = 6
integer, parameter :: MPI_COMBINER_HVECTOR_INTEGER = 5
integer, parameter :: MPI_COMBINER_INDEXED = 7
integer, parameter :: MPI_COMBINER_INDEXED_BLOCK = 10
integer, parameter :: MPI_COMBINER_NAMED = 1
integer, parameter :: MPI_COMBINER_RESIZED = 18
integer, parameter :: MPI_COMBINER_STRUCT = 12
integer, parameter :: MPI_COMBINER_STRUCT_INTEGER = 11
integer, parameter :: MPI_COMBINER_SUBARRAY = 13
integer, parameter :: MPI_COMBINER_VECTOR = 4
integer, parameter :: MPI_COMM_NULL = 67108864
integer, parameter :: MPI_COMM_SELF = 1140850689
integer, parameter :: MPI_COMM_TYPE_SHARED = 1
integer, parameter :: MPI_COMM_WORLD = 1140850688
integer, parameter :: MPI_COMPLEX = 1275070494
integer, parameter :: MPI_COMPLEX16 = 1275072554
integer, parameter :: MPI_COMPLEX32 = 1275076652
integer, parameter :: MPI_COMPLEX8 = 1275070504
integer, parameter :: MPI_CONGRUENT = 1
integer, parameter :: MPI_COUNT = 1275070533
integer, parameter :: MPI_COUNT_KIND = 8
integer, parameter :: MPI_CXX_BOOL = 1275068723
integer, parameter :: MPI_CXX_DOUBLE_COMPLEX = 1275072565
integer, parameter :: MPI_CXX_FLOAT_COMPLEX = 1275070516
integer, parameter :: MPI_CXX_LONG_DOUBLE_COMPLEX = 1275076662
integer, parameter :: MPI_C_BOOL = 1275068735
integer, parameter :: MPI_C_COMPLEX = 1275070528
integer, parameter :: MPI_C_DOUBLE_COMPLEX = 1275072577
integer, parameter :: MPI_C_FLOAT_COMPLEX = 1275070528
integer, parameter :: MPI_C_LONG_DOUBLE_COMPLEX = 1275076674
integer, parameter :: MPI_DATATYPE_NULL = 201326592
integer, parameter :: MPI_DISPLACEMENT_CURRENT = -54278278
integer, parameter :: MPI_DISTRIBUTE_BLOCK = 121
integer, parameter :: MPI_DISTRIBUTE_CYCLIC = 122
integer, parameter :: MPI_DISTRIBUTE_DFLT_DARG = -49767
integer, parameter :: MPI_DISTRIBUTE_NONE = 123
integer, parameter :: MPI_DIST_GRAPH = 3
integer, parameter :: MPI_DOUBLE = 1275070475
integer, parameter :: MPI_DOUBLE_COMPLEX = 1275072546
integer, parameter :: MPI_DOUBLE_INT = -1946157055
integer, parameter :: MPI_DOUBLE_PRECISION = 1275070495
integer :: MPI_ERRCODES_IGNORE(1)
integer, parameter :: MPI_ERRHANDLER_NULL = 335544320
integer, parameter :: MPI_ERROR = 5
integer, parameter :: MPI_ERRORS_ARE_FATAL = 1409286144
integer, parameter :: MPI_ERRORS_RETURN = 1409286145
integer, parameter :: MPI_ERR_ACCESS = 20
integer, parameter :: MPI_ERR_AMODE = 21
integer, parameter :: MPI_ERR_ARG = 12
integer, parameter :: MPI_ERR_ASSERT = 53
integer, parameter :: MPI_ERR_BAD_FILE = 22
integer, parameter :: MPI_ERR_BASE = 46
integer, parameter :: MPI_ERR_BUFFER = 1
integer, parameter :: MPI_ERR_COMM = 5
integer, parameter :: MPI_ERR_CONVERSION = 23
integer, parameter :: MPI_ERR_COUNT = 2
integer, parameter :: MPI_ERR_DIMS = 11
integer, parameter :: MPI_ERR_DISP = 52
integer, parameter :: MPI_ERR_DUP_DATAREP = 24
integer, parameter :: MPI_ERR_FILE = 27
integer, parameter :: MPI_ERR_FILE_EXISTS = 25
integer, parameter :: MPI_ERR_FILE_IN_USE = 26
integer, parameter :: MPI_ERR_GROUP = 8
integer, parameter :: MPI_ERR_INFO = 28
integer, parameter :: MPI_ERR_INFO_KEY = 29
integer, parameter :: MPI_ERR_INFO_NOKEY = 31
integer, parameter :: MPI_ERR_INFO_VALUE = 30
integer, parameter :: MPI_ERR_INTERN = 16
integer, parameter :: MPI_ERR_IN_STATUS = 17
integer, parameter :: MPI_ERR_IO = 32
integer, parameter :: MPI_ERR_KEYVAL = 48
integer, parameter :: MPI_ERR_LASTCODE = 1073741823
integer, parameter :: MPI_ERR_LOCKTYPE = 47
integer, parameter :: MPI_ERR_NAME = 33
integer, parameter :: MPI_ERR_NOT_SAME = 35
integer, parameter :: MPI_ERR_NO_MEM = 34
integer, parameter :: MPI_ERR_NO_SPACE = 36
integer, parameter :: MPI_ERR_NO_SUCH_FILE = 37
integer, parameter :: MPI_ERR_OP = 9
integer, parameter :: MPI_ERR_OTHER = 15
integer, parameter :: MPI_ERR_PENDING = 18
integer, parameter :: MPI_ERR_PORT = 38
integer, parameter :: MPI_ERR_QUOTA = 39
integer, parameter :: MPI_ERR_RANK = 6
integer, parameter :: MPI_ERR_READ_ONLY = 40
integer, parameter :: MPI_ERR_REQUEST = 19
integer, parameter :: MPI_ERR_RMA_ATTACH = 56
integer, parameter :: MPI_ERR_RMA_CONFLICT = 49
integer, parameter :: MPI_ERR_RMA_FLAVOR = 58
integer, parameter :: MPI_ERR_RMA_RANGE = 55
integer, parameter :: MPI_ERR_RMA_SHARED = 57
integer, parameter :: MPI_ERR_RMA_SYNC = 50
integer, parameter :: MPI_ERR_ROOT = 7
integer, parameter :: MPI_ERR_SERVICE = 41
integer, parameter :: MPI_ERR_SIZE = 51
integer, parameter :: MPI_ERR_SPAWN = 42
integer, parameter :: MPI_ERR_TAG = 4
integer, parameter :: MPI_ERR_TOPOLOGY = 10
integer, parameter :: MPI_ERR_TRUNCATE = 14
integer, parameter :: MPI_ERR_TYPE = 3
integer, parameter :: MPI_ERR_UNKNOWN = 13
integer, parameter :: MPI_ERR_UNSUPPORTED_DATAREP = 43
integer, parameter :: MPI_ERR_UNSUPPORTED_OPERATION = 44
integer, parameter :: MPI_ERR_WIN = 45
integer, parameter :: MPI_FILE_NULL = 0
integer, parameter :: MPI_FLOAT = 1275069450
integer, parameter :: MPI_FLOAT_INT = -1946157056
integer, parameter :: MPI_GRAPH = 1
integer, parameter :: MPI_GROUP_EMPTY = 1207959552
integer, parameter :: MPI_GROUP_NULL = 134217728
integer, parameter :: MPI_HOST = 1681915908
integer, parameter :: MPI_IDENT = 0
integer, parameter :: MPI_INFO_ENV = 1543503873
integer, parameter :: MPI_INFO_NULL = 469762048
integer, parameter :: MPI_INT = 1275069445
integer, parameter :: MPI_INT16_T = 1275068984
integer, parameter :: MPI_INT32_T = 1275069497
integer, parameter :: MPI_INT64_T = 1275070522
integer, parameter :: MPI_INT8_T = 1275068727
integer, parameter :: MPI_INTEGER = 1275069467
integer, parameter :: MPI_INTEGER1 = 1275068717
integer, parameter :: MPI_INTEGER16 = MPI_DATATYPE_NULL
integer, parameter :: MPI_INTEGER2 = 1275068975
integer, parameter :: MPI_INTEGER4 = 1275069488
integer, parameter :: MPI_INTEGER8 = 1275070513
integer, parameter :: MPI_INTEGER_KIND = 4
integer :: MPI_IN_PLACE
integer, parameter :: MPI_IO = 1681915910
integer, parameter :: MPI_KEYVAL_INVALID = 603979776
integer, parameter :: MPI_LAND = 1476395013
integer, parameter :: MPI_LASTUSEDCODE = 1681915916
integer, parameter :: MPI_LB = 1275068432
integer, parameter :: MPI_LOCK_EXCLUSIVE = 234
integer, parameter :: MPI_LOCK_SHARED = 235
integer, parameter :: MPI_LOGICAL = 1275069469
integer, parameter :: MPI_LONG = 1275070471
integer, parameter :: MPI_LONG_DOUBLE = 1275072524
integer, parameter :: MPI_LONG_DOUBLE_INT = -1946157052
integer, parameter :: MPI_LONG_INT = -1946157054
integer, parameter :: MPI_LONG_LONG = 1275070473
integer, parameter :: MPI_LONG_LONG_INT = 1275070473
integer, parameter :: MPI_LOR = 1476395015
integer, parameter :: MPI_LXOR = 1476395017
integer, parameter :: MPI_MAX = 1476395009
integer, parameter :: MPI_MAXLOC = 1476395020
integer, parameter :: MPI_MAX_DATAREP_STRING = 127
integer, parameter :: MPI_MAX_ERROR_STRING = 512-1
integer, parameter :: MPI_MAX_INFO_KEY = 254
integer, parameter :: MPI_MAX_INFO_VAL = 1023
integer, parameter :: MPI_MAX_LIBRARY_VERSION_STRING = 8192-1
integer, parameter :: MPI_MAX_OBJECT_NAME = 127
integer, parameter :: MPI_MAX_PORT_NAME = 255
integer, parameter :: MPI_MAX_PROCESSOR_NAME = 128-1
integer, parameter :: MPI_MESSAGE_NO_PROC = 1811939328
integer, parameter :: MPI_MESSAGE_NULL = 738197504
integer, parameter :: MPI_MIN = 1476395010
integer, parameter :: MPI_MINLOC = 1476395019
integer, parameter :: MPI_MODE_APPEND = 128
integer, parameter :: MPI_MODE_CREATE = 1
integer, parameter :: MPI_MODE_DELETE_ON_CLOSE = 16
integer, parameter :: MPI_MODE_EXCL = 64
integer, parameter :: MPI_MODE_NOCHECK = 1024
integer, parameter :: MPI_MODE_NOPRECEDE = 8192
integer, parameter :: MPI_MODE_NOPUT = 4096
integer, parameter :: MPI_MODE_NOSTORE = 2048
integer, parameter :: MPI_MODE_NOSUCCEED = 16384
integer, parameter :: MPI_MODE_RDONLY = 2
integer, parameter :: MPI_MODE_RDWR = 8
integer, parameter :: MPI_MODE_SEQUENTIAL = 256
integer, parameter :: MPI_MODE_UNIQUE_OPEN = 32
integer, parameter :: MPI_MODE_WRONLY = 4
integer, parameter :: MPI_NO_OP = 1476395022
integer, parameter :: MPI_OFFSET = 1275070532
integer, parameter :: MPI_OFFSET_KIND = 8
integer, parameter :: MPI_OP_NULL = 402653184
integer, parameter :: MPI_ORDER_C = 56
integer, parameter :: MPI_ORDER_FORTRAN = 57
integer, parameter :: MPI_PACKED = 1275068687
integer, parameter :: MPI_PROC_NULL = -1
integer, parameter :: MPI_PROD = 1476395012
integer, parameter :: MPI_REAL = 1275069468
integer, parameter :: MPI_REAL16 = 1275072555
integer, parameter :: MPI_REAL4 = 1275069479
integer, parameter :: MPI_REAL8 = 1275070505
integer, parameter :: MPI_REPLACE = 1476395021
integer, parameter :: MPI_REQUEST_NULL = 738197504
integer, parameter :: MPI_ROOT = -3
integer, parameter :: MPI_SEEK_CUR = 602
integer, parameter :: MPI_SEEK_END = 604
integer, parameter :: MPI_SEEK_SET = 600
integer, parameter :: MPI_SHORT = 1275068931
integer, parameter :: MPI_SHORT_INT = -1946157053
integer, parameter :: MPI_SIGNED_CHAR = 1275068696
integer, parameter :: MPI_SIMILAR = 2
integer, parameter :: MPI_SOURCE = 3
integer :: MPI_STATUSES_IGNORE(MPI_STATUS_SIZE,1)
integer :: MPI_STATUS_IGNORE(MPI_STATUS_SIZE)
integer, parameter :: MPI_STATUS_SIZE = 5
logical :: MPI_SUBARRAYS_SUPPORTED
integer, parameter :: MPI_SUBVERSION = 1
integer, parameter :: MPI_SUCCESS = 0
integer, parameter :: MPI_SUM = 1476395011
integer, parameter :: MPI_TAG = 4
integer, parameter :: MPI_TAG_UB = 1681915906
integer, parameter :: MPI_THREAD_FUNNELED = 1
integer, parameter :: MPI_THREAD_MULTIPLE = 3
integer, parameter :: MPI_THREAD_SERIALIZED = 2
integer, parameter :: MPI_THREAD_SINGLE = 0
integer, parameter :: MPI_TYPECLASS_COMPLEX = 3
integer, parameter :: MPI_TYPECLASS_INTEGER = 2
integer, parameter :: MPI_TYPECLASS_REAL = 1
integer, parameter :: MPI_UB = 1275068433
integer, parameter :: MPI_UINT16_T = 1275068988
integer, parameter :: MPI_UINT32_T = 1275069501
integer, parameter :: MPI_UINT64_T = 1275070526
integer, parameter :: MPI_UINT8_T = 1275068731
integer, parameter :: MPI_UNDEFINED = (-32766)
integer, parameter :: MPI_UNEQUAL = 3
integer, parameter :: MPI_UNIVERSE_SIZE = 1681915914
integer, parameter :: MPI_UNSIGNED = 1275069446
integer, parameter :: MPI_UNSIGNED_CHAR = 1275068674
integer, parameter :: MPI_UNSIGNED_LONG = 1275070472
integer, parameter :: MPI_UNSIGNED_LONG_LONG = 1275070489
integer, parameter :: MPI_UNSIGNED_SHORT = 1275068932
integer :: MPI_UNWEIGHTED
integer, parameter :: MPI_VERSION = 3
integer, parameter :: MPI_WCHAR = 1275069454
integer :: MPI_WEIGHTS_EMPTY
integer, parameter :: MPI_WIN_BASE = 1711276034
integer, parameter :: MPI_WIN_CREATE_FLAVOR = 1711276040
integer, parameter :: MPI_WIN_DISP_UNIT = 1711276038
integer, parameter :: MPI_WIN_FLAVOR_ALLOCATE = 2
integer, parameter :: MPI_WIN_FLAVOR_CREATE = 1
integer, parameter :: MPI_WIN_FLAVOR_DYNAMIC = 3
integer, parameter :: MPI_WIN_FLAVOR_SHARED = 4
integer, parameter :: MPI_WIN_MODEL = 1711276042
integer, parameter :: MPI_WIN_NULL = 536870912
integer, parameter :: MPI_WIN_SEPARATE = 1
integer, parameter :: MPI_WIN_SIZE = 1711276036
integer, parameter :: MPI_WIN_UNIFIED = 2
integer, parameter :: MPI_WTIME_IS_GLOBAL = 1681915912
complex, allocatable :: bufr(:)
integer(kind=int64) :: ierror
integer(kind=int64) :: iter
integer(kind=int64) :: msg_size
complex, allocatable :: u(:,:,:,:)
complex, allocatable :: ur(:,:,:,:)
integer(kind=int64) :: x
integer(kind=int64) :: y
integer(kind=int64) :: z
Subroutines
subroutine transpose_X_Y()
Arguments
None
subroutine transpose_Y_X()
Arguments
None
Source Code
program mpi_distributed_transpose
  !(***********************************************************************************************************
  !                   m a i n   p r o g r a m
  !***********************************************************************************************************)
      use mpi_run_size
      implicit none
      include 'mpif.h'
      complex, allocatable ::  u(:,:,:,:)    ! u(nz,4,first_x:last_x,ny)    !(*-- ny = my * num_nodes --*)
      complex, allocatable ::  ur(:,:,:,:)   !ur(nz,4,first_y:last_y,nx/2)  !(*-- nx/2 = mx * num_nodes --*)
      complex, allocatable :: bufr(:)
      integer(int64) :: x, y, z, msg_size, iter
      integer(int64) :: ierror
  call MPI_INIT(ierror)
  call MPI_COMM_RANK(MPI_COMM_WORLD, my_node, ierror)
  call MPI_COMM_SIZE(MPI_COMM_WORLD, num_nodes, ierror)
      if( my_node == 0 ) then
       !write(6,fmt="(A)") "nx,ny,nz : "
       !read(5,*) nx, ny, nz
       nx=32; ny=32; nz=32
      end if
        call MPI_BARRIER(MPI_COMM_WORLD, ierror)  !-- other nodes wait for broadcast!
        call MPI_BCAST( nx, 1, MPI_INT, 0,MPI_COMM_WORLD, ierror )
        call MPI_BCAST( ny, 1, MPI_INT, 0,MPI_COMM_WORLD, ierror )
        call MPI_BCAST( nz, 1, MPI_INT, 0,MPI_COMM_WORLD, ierror )
       if ( mod(ny,num_nodes) == 0)  then;   my = ny / num_nodes
                                    else;   write(6,*) "node ", my_node, " ny not multiple of num_nodes";     stop
      end if
      if ( mod(nx/2,num_nodes) == 0)  then;   mx = nx/2 / num_nodes
                                    else;   write(6,*) "node ", my_node, "nx/2 not multiple of num_nodes";    stop
      end if
      first_y = my_node*my + 1;   last_y  = my_node*my + my
      first_x = my_node*mx + 1;   last_x  = my_node*mx + mx
      msg_size = nz*4*mx*my     !-- message size (complex data items
      allocate (  u(nz , 4 , first_x:last_x , ny)   )   !(*-- y-z planes --*)
      allocate ( ur(nz , 4 , first_y:last_y , nx/2) )   !(*-- x-z planes --*)
      allocate ( bufr(msg_size) )
!---------  initialize data u (mx y-z planes per image) ----------
        do x = first_x, last_x
            do y = 1, ny
                do z = 1, nz
                    u(z,1,x,y) = x
                    u(z,2,x,y) = y
                    u(z,3,x,y) = z
                end do
            end do
        end do
    tran_time = 0
    do iter = 1, 2  !--- 2 transform pairs per second-order time step
!---------  transpose data u -> ur (mx y-z planes to my x-z planes per image)  --------
      ur = 0
      call transpose_X_Y
!--------- test data ur (my x-z planes per image) ----------
         do x = 1, nx/2
            do y = first_y, last_y
                do z = 1, nz
                    if ( real(ur(z,1,y,x)) /= x .or. real(ur(z,2,y,x)) /= y .or. real(ur(z,3,y,x)) /= z )then
                         write(6,fmt="(A,i3,3(6X,A,f7.3,i4))") "transpose_X_Y failed:  image ", my_node &
                            , " X ",real(ur(z,1,y,x)),x, "  Y ",real(ur(z,2,y,x)),y, "  Z ", real(ur(z,3,y,x)),z
                        stop
                    end if
                end do
            end do
        end do
!---------  transpose data ur -> u (my x-z planes to mx y-z planes per image)  --------
      u = 0
      call transpose_Y_X
!--------- test data u (mx y-z planes per image) ----------
         do x = first_x, last_x
            do y = 1, ny
                do z = 1, nz
                    if ( real(u(z,1,x,y)) /= x .or. real(u(z,2,x,y)) /= y .or. real(u(z,3,x,y)) /= z )then
                         write(6,fmt="(A,i3,3(6X,A,f7.3,i4))") "transpose_Y_X failed:  image ", my_node &
                            , " X ",real(u(z,1,y,x)),x, "  Y ",real(u(z,2,y,x)),y, "  Z ", real(u(z,3,y,x)),z
                        stop
                    end if
                end do
            end do
        end do
    end do
call MPI_BARRIER(MPI_COMM_WORLD, ierror)
        if( my_node == 0 )  write(6,fmt="(A,f8.3)")  "test passed:  tran_time ", tran_time
    deallocate ( bufr, ur, u)
!=========================   end of main executable  =============================
contains
!-------------   out-of-place transpose data_s --> data_r  ----------------------------
 subroutine transpose_X_Y
    use mpi_run_size
    implicit none
    integer(int64) :: to, from, send_tag, recv_tag
    integer :: stage, idr(0:num_nodes-1), ids(0:num_nodes-1)
    integer(int64) :: send_status(MPI_STATUS_SIZE), recv_status(MPI_STATUS_SIZE)
    character*(MPI_MAX_ERROR_STRING) errs
    call MPI_BARRIER(MPI_COMM_WORLD, ierror)   !--  wait for other nodes to finish compute
    tran_time = tran_time - WALLTIME()
!--------------   transpose my image's block (no communication needed)  ------------------
    call mpi_copy3 (    u(1,1,first_x,1+my_node*my) &                   !-- intra-node transpose
                ,  ur(1,1,first_y,1+my_node*mx) &                   !-- no inter-node transpose needed
                ,   nz*3, 1_8, 1_8        &                                 !-- note: only 3 of 4 words needed
                ,   mx, nz*4, nz*4*my &
                ,   my, nz*4*mx, nz*4 )
#define RECEIVE
#ifdef RECEIVE
!--------------   issue all block sends ... tags = 256*dst_image+src_image  ------------------
    do stage = 1, num_nodes-1
        to = mod( my_node+stage, num_nodes )
        send_tag = 256*to + my_node
        call MPI_ISSEND ( u(1,1,first_x,1+to*my) &
                        ,   msg_size*2,  MPI_REAL,  to, send_tag,  MPI_COMM_WORLD,  ids(stage),  ierror)
    end do
!--------------   receive and transpose other image's block  ------------------
    do stage = 1, num_nodes-1   !-- process receives in order
        from = mod( my_node+stage, num_nodes )
        recv_tag = 256*my_node + from
        call MPI_RECV  ( bufr &
                        ,   msg_size*2,  MPI_REAL,  from, recv_tag,  MPI_COMM_WORLD,  recv_status,  ierror)
        call mpi_copy3 ( bufr, ur(1,1,first_y,1+from*mx)  &                !-- intra-node transpose from buffer
                        ,   nz*3, 1_8, 1_8        &                             !-- note: only 3 of 4 words needed
                        ,   mx, nz*4, nz*4*my &
                        ,   my, nz*4*mx, nz*4 )
    end do
#else
!--------------   issue all block receives ... tags = 256*dst_image+src_image  ------------------
    do stage = 1, num_nodes-1
        from = mod( my_node+stage, num_nodes )
        recv_tag = 256*my_node + from
        call MPI_IRECV  ( ur(1,1,first_y,1+from*mx) &
                        ,   msg_size*2,  MPI_REAL,  from, recv_tag,  MPI_COMM_WORLD,  idr(stage),  ierror)
    end do
!--------------   issue all block sends ... tags = 256*dst_image+src_image  ------------------
    do stage = 1, num_nodes-1   !-- process sends in order
        to = mod( my_node+stage, num_nodes )
        send_tag = 256*to + my_node
        call mpi_copy3 ( u(1,1,first_x,1+to*my), bufr &                !-- intra-node transpose from buffer
                ,   nz*3, 1_8, 1_8        &                             !-- note: only 3 of 4 words needed
                ,   mx, nz*4, nz*4*my &
                ,   my, nz*4*mx, nz*4 )
        call MPI_SEND ( bufr &
                        ,   msg_size*2,  MPI_REAL,  to, send_tag,  MPI_COMM_WORLD,  ierror)
    end do
!--------------   wait on receives   ------------------
    do stage = 1, num_nodes-1
        call MPI_WAIT( idr(stage),  recv_status,  ierror )
    end do
#endif
call MPI_BARRIER(MPI_COMM_WORLD, ierror)     !--  wait for other nodes to finish transpose
    tran_time = tran_time + WALLTIME()
! deallocate(ids,idr)
 end  subroutine transpose_X_Y
!-------------   out-of-place transpose data_r --> data_s  ----------------------------
 subroutine transpose_Y_X
    use mpi_run_size
    implicit none
    integer(int64) :: to, from, send_tag, recv_tag
    integer :: stage, idr(0:num_nodes-1), ids(0:num_nodes-1)
    character*(MPI_MAX_ERROR_STRING) errs
    integer(int64) :: send_status(MPI_STATUS_SIZE), recv_status(MPI_STATUS_SIZE)
    call MPI_BARRIER(MPI_COMM_WORLD, ierror)   !--  wait for other nodes to finish compute
    tran_time = tran_time - WALLTIME()
!--------------   transpose my image's block (no communication needed)  ------------------
    call mpi_copy3 (   ur(1,1,first_y,1+my_node*mx) &                   !-- intra-node transpose
                ,   u(1,1,first_x,1+my_node*my) &                   !-- no inter-node transpose needed
                ,   nz*4, 1_8, 1_8        &                                 !-- note: all 4 words needed
                ,   my, nz*4, nz*4*mx &
                ,   mx, nz*4*my, nz*4 )
#define RECEIVE
#ifdef RECEIVE
!--------------   issue all block sends ... tags = 256*dst_image+src_image  ------------------
    do stage = 1, num_nodes-1
        to = mod( my_node+stage, num_nodes )
        send_tag = 256*to + my_node
        call MPI_ISSEND ( ur(1,1,first_y,1+to*mx)    &
                        ,   msg_size*2,  MPI_REAL,  to, send_tag,  MPI_COMM_WORLD,  ids(stage),  ierror)
    end do
!--------------   transpose other image's block (get block then transpose it)  ------------------
    do stage = 1, num_nodes-1   !-- process receives in order
        from = mod( my_node+stage, num_nodes )
        recv_tag = 256*my_node + from
        call MPI_RECV  ( bufr  &
                        ,   msg_size*2,  MPI_REAL,  from, recv_tag,  MPI_COMM_WORLD,  recv_status,  ierror)
        call mpi_copy3 ( bufr, u(1,1,first_x,1+from*my)  &                 !-- intra-node transpose from buffer
                    ,   nz*4, 1_8, 1_8        &
                    ,   my, nz*4, nz*4*mx &
                    ,   mx, nz*4*my, nz*4 )
    end do
#else
!--------------   issue all block receives ... tags = 256*dst_image+src_image  ------------------
    do stage = 1, num_nodes-1
        from = mod( my_node+stage, num_nodes )
        recv_tag = 256*my_node + from
        call MPI_IRECV  ( u(1,1,first_x,1+from*my) &
                        ,   msg_size*2,  MPI_REAL,  from, recv_tag,  MPI_COMM_WORLD,  idr(stage),  ierror)
    end do
!--------------   issue all block sends ... tags = 256*dst_image+src_image  ------------------
    do stage = 1, num_nodes-1   !-- process sends in order
        to = mod( my_node+stage, num_nodes )
        send_tag = 256*to + my_node
        call mpi_copy3 ( ur(1,1,first_y,1+to*mx), bufr &                !-- intra-node transpose from buffer
                ,   nz*4, 1_8, 1_8        &                                 !-- note: all 4 words needed
                ,   my, nz*4, nz*4*mx &
                ,   mx, nz*4*my, nz*4 )
        call MPI_SEND ( bufr &
                        ,   msg_size*2,  MPI_REAL,  to, send_tag,  MPI_COMM_WORLD,  ierror)
    end do
!--------------   wait on receives   ------------------
    do stage = 1, num_nodes-1
        call MPI_WAIT( idr(stage),  recv_status,  ierror )
    end do
#endif
    call MPI_BARRIER(MPI_COMM_WORLD, ierror)     !--  wait for other nodes to finish transpose
    tran_time = tran_time + WALLTIME()
 !   deallocate(ids,idr)
 end  subroutine transpose_Y_X
end program mpi_distributed_transpose
Call graph
mpi_distributed_transpose calls transpose_y_x, mpi_comm_rank, mpi_comm_size, mpi_barrier, mpi_bcast, transpose_x_y, mpi_init
transpose_y_x calls mpi_barrier, mpi_recv, walltime, mpi_issend, mpi_copy3
transpose_x_y calls mpi_barrier, mpi_recv, walltime, mpi_issend, mpi_copy3