mshear – OpenCoarrays
mshear Program
Source File
Uses:
run_size
****************)
Calls
Interfaces
interface
subroutine solve_navier_stokes()
Arguments
None
Source Code
program mshear
  !(***********************************************************************************************************
  !                   m a i n   p r o g r a m
  !***********************************************************************************************************)
      use run_size
      implicit none
      interface
        subroutine solve_navier_stokes
        end subroutine solve_navier_stokes
      end interface
  call MPI_INIT(ierror)
  call MPI_COMM_RANK(MPI_COMM_WORLD, my_node, ierror)
  call MPI_COMM_SIZE(MPI_COMM_WORLD, num_nodes, ierror)
      if( my_node == 0 ) then
        write(6,*) "nx,ny,nz : ";               read(5,*) nx, ny, nz
        if ( mod(nx/2,num_nodes) /= 0) then;    write(6,*) "nx/2 not multiple of num_nodes";    stop;   end if
        if ( mod(ny,num_nodes) /= 0) then;      write(6,*) " ny not multiple of num_nodes";     stop;   end if
        write(6,*) "viscos, shear : ";          read(5,*) viscos, shear
        write(6,*) "b11 b22 b33 b12 : ";        read(5,*) b11, b22, b33, b12
        write(6,*) "nsteps, output_step : ";    read(5,*) nsteps, output_step
        write(6,fmt="(3(A,i4))") "nx =",nx,   "   ny =",ny,   "   nz =",nz
        write(6,fmt="(2(A,f7.3))") "viscos = ", viscos, "      shear = ", shear
        write(6,fmt="(A,4f7.3)") "b11 b22 b33 b12 = ", b11, b22, b33, b12
        write(6,fmt="(2(A,i6))") "nsteps = ", nsteps, "       output_step = ", output_step
        write(6,fmt="(A,i4,A)") "----------------- running on ", num_nodes, " images -------------------"
      end if
        call MPI_BCAST( nx, 1, MPI_INT, 0, MPI_COMM_WORLD, ierror )
        call MPI_BCAST( ny, 1, MPI_INT, 0, MPI_COMM_WORLD, ierror )
        call MPI_BCAST( nz, 1, MPI_INT, 0, MPI_COMM_WORLD, ierror )
        call MPI_BCAST( viscos, 1, MPI_FLOAT, 0, MPI_COMM_WORLD, ierror )
        call MPI_BCAST( shear, 1, MPI_FLOAT, 0, MPI_COMM_WORLD, ierror )
        call MPI_BCAST( b11, 1, MPI_FLOAT, 0, MPI_COMM_WORLD, ierror )
        call MPI_BCAST( b22, 1, MPI_FLOAT, 0, MPI_COMM_WORLD, ierror )
        call MPI_BCAST( b33, 1, MPI_FLOAT, 0, MPI_COMM_WORLD, ierror )
        call MPI_BCAST( b12, 1, MPI_FLOAT, 0, MPI_COMM_WORLD, ierror )
        call MPI_BCAST( nsteps, 1, MPI_INT, 0, MPI_COMM_WORLD, ierror )
        call MPI_BCAST( output_step, 1, MPI_INT, 0, MPI_COMM_WORLD, ierror )
        call MPI_BARRIER(MPI_COMM_WORLD, ierror)
         mx = nx/2 / num_nodes;  first_x = my_node*mx + 1;   last_x  = my_node*mx + mx
        my = ny / num_nodes;    first_y = my_node*my + 1;   last_y  = my_node*my + my
    call solve_navier_stokes
end program mshear
Call graph
mshear calls mpi_comm_rank, solve_navier_stokes, mpi_barrier, mpi_bcast, mpi_comm_size, mpi_init