#!/bin/sh
SOURCE_PATH=../opencoarrays
EXTRA_ARGS=$@

rm -rf CMakeCache.txt CMakeFiles
cmake \
  -D CMAKE_BUILD_TYPE:STRING=DEBUG \
  -D CMAKE_C_COMPILER:FILEPATH=gcc \
  -D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
  -D CMAKE_INSTALL_PREFIX:PATH=${PWD}/lib \
$EXTRA_ARGS \
$SOURCE_PATH
