#!/bin/bash
# See https://github.com/rossf7/label-schema-automated-build
#     or https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1#.wgkzfdnfr
#     for more details.

# $IMAGE_NAME var is injected into the build so the tag is correct.

set -o verbose
set -o pipefail
set -o errexit
set -x

git fetch -v --all --tags
git fetch -v --all --depth=9999999 --update-shallow
git tag --list
git branch

echo "Info: value of IMAGE_NAME = ${IMAGE_NAME:-<unset>}"

d_repo='sourceryinstitute/OpenCoarrays'
d_git_remotes=("$(git remote show)")
echo "${#d_git_remotes[@]} git remotes found."
n_remotes=${#d_git_remotes[@]}
if (( n_remotes > 0 )) ; then
    echo "Using remote: ${d_git_remotes[0]}"
    d_vcs_url="$(git remote -v | awk '/origin/ {print $2; exit}')"
fi

if [[ -z "${d_vcs_url:-}" ]]; then
    d_vcs_url="https://github.com/${DOCKER_REPO:-${d_repo}}"
fi

branch_name="$(git symbolic-ref -q HEAD)" || true
branch_name="${branch_name##refs/heads/}"
branch_name="${branch_name:-DETACHED-HEAD}"

d_vcs_describe="$(git describe --tags --always || true)"
d_tag="${IMAGE_NAME##*:}"
d_tag="${d_tag:-${branch_name}-$(date +%s)}"
d_vcs_tag="$(git rev-parse --short=12 --verify HEAD)"

if [[ -n "${IMAGE_NAME:-}" ]]; then
  export RUN_TESTS=false
fi


opencoarrays_version="${d_vcs_describe}"
if [[ -n "${open_coarrays_version:-}" ]]; then
  opencoarrays_version=1.9.2
fi

echo "Build hook running"
docker build --build-arg OPENCOARRAYS_VERSION="${opencoarrays_version}" \
             --build-arg RUN_TESTS=${RUN_TESTS:-true} \
             --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             --build-arg VCS_REF="${SOURCE_COMMIT:-$(git rev-parse --short HEAD)}" \
             --build-arg VCS_URL="${d_vcs_url}" \
	     --build-arg VCS_VERSION="${d_vcs_describe:-${d_tag}}" \
	     --rm \
	     --pull \
             -t "${IMAGE_NAME:-$(tr '[:upper:]' '[:lower:]' <<< "${d_repo}_jupyter"):latest}" .
docker tag "${IMAGE_NAME:-$(tr '[:upper:]' '[:lower:]' <<< "${d_repo}_jupyter"):latest}" "${IMAGE_NAME:-$(tr '[:upper:]' '[:lower:]' <<< "${d_repo}_jupyter"):${d_vcs_tag}}"
