name: Windows CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
    # defaults:
    #   run:
    #     shell: msys2 {0}

    env:
      FC: gfortran
      CC: gcc

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      uses: msys2/setup-msys2@v2
      with:
        update: true
        path-type: inherit
        install: >-
          mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-gcc

    - name: setup-mpi
      id: setup-mpi
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: intelmpi

    - name: MPI info
      run: |
        echo "${{ steps.setup-mpi.outputs.mpi }}"
        mpiexec --version
        ls $env:I_MPI_ROOT
        ls "$env:I_MPI_ROOT\bin"
        ls "$env:I_MPI_ROOT\lib"
        mpifc.bat -show
        mpicc.bat -show
	echo $HOME
	echo $env:HOME
	echo $home
	echo $env:home
	echo "$env:home/some/path"

    - name: Build and Test
      run: |
        $ErrorActionPreference = "Stop"
        Set-StrictMode -Version Latest
        $ErrorActionPreference = "Stop"
        $PSDefaultParameterValues['*:ErrorAction']='Stop'
        function ThrowOnNativeFailure {
            if (-not $?)
            {
                throw 'Native Failure'
            }
        }
        mkdir build
        $env:VERBOSE = 1
        make -Wdev -G "Unix Makefiles" -S . -B build -DCMAKE_INSTALL_PREFIX="$HOME\apps\OpenCoarrays" -DCMAKE_BUILD_TYPE:STRING="Debug"
        ThrowOnNativeFailure
        cmake --build build -j
        ThrowOnNativeFailure
        cmake --build build -j
        ThrowOnNativeFailure
        cmake --build build -t install -j
        ThrowOnNativeFailure
        ctest --test-dir build --output-on-failure --schedule-random --repeat-until-fail 1 --timeout 200
        ThrowOnNativeFailure
        echo "$HOME\apps\OpenCoarrays\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        ThrowOnNativeFailure
        $env:PATH += ";$HOME\apps\OpenCoarrays\bin"
        ThrowOnNativeFailure
        cafrun --show
        ThrowOnNativeFailure
        caf --show
        ThrowOnNativeFailure
        cafrun --version
        ThrowOnNativeFailure
        caf --version
        ThrowOnNativeFailure
        cd build
        make uninstall
        ThrowOnNativeFailure
