name: Windows CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-latest
    strategy:
      fail-fast: true
    # defaults:
    #   run:
    #     shell: msys2 {0}

    env:
      FC: gfortran
      CC: gcc

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Dependencies
      uses: msys2/setup-msys2@v2
      with:
        update: true
        path-type: inherit
        install: >-
          mingw-w64-x86_64-gcc-fortran mingw-w64-x86_64-gcc

    - name: setup-mpi
      id: setup-mpi
      uses: mpi4py/setup-mpi@v1
      with:
        mpi: intelmpi

    - name: MPI info
      run: |
        echo "${{ steps.setup-mpi.outputs.mpi }}"
        mpiexec --version
        ls $env:I_MPI_ROOT
        ls $env:I_MPI_ROOT\bin
        ls $env:I_MPI_ROOT\lib
        mpifc.bat -show
        mpicc.bat -show

    - name: Build and Test
      run: |
        mkdir build
        cmake -Wdev -G "Unix Makefiles" -S . -B build -DCMAKE_INSTALL_PREFIX=$env:HOME\apps\OpenCoarrays -DCMAKE_BUILD_TYPE:STRING="Debug"
        cmake --build build -j
        cmake --build build -t install -j
        ctest --test-dir build --output-on-failure --schedule-random --repeat-until-fail 1 --timeout 200
        echo "$env:HOME\apps\OpenCoarrays\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        $env:PATH += ";$env:HOME/apps/OpenCoarrays/bin"
        cafrun --show
        caf --show
        cafrun --version
        caf --version
        cd build
        make uninstall
